# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macOS-10.13'

steps:
- bash: 'sudo xcode-select -s /Applications/Xcode_10.1.app/Contents/Developer'
- bash: 'swift test'
