#if !canImport(ObjectiveC)
import XCTest

extension TypeLexersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TypeLexersTests = [
        ("testLexDouble", testLexDouble),
        ("testLexFloat", testLexFloat),
        ("testLexInt8", testLexInt8),
        ("testLexInteger", testLexInteger),
        ("testLexUInt8", testLexUInt8),
        ("testPerformance", testPerformance),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TypeLexersTests.__allTests__TypeLexersTests),
    ]
}
#endif
