//
//  URLParseSampleTests.swift
//  URLParseSampleTests
//
//  Created by Luiz Fernando Silva on 23/09/17.
//

import XCTest
import URLParseSample
import MiniLexer

class URLParseSampleTests: XCTestCase {
    
    func testSimpleParse() {
        let urlString = "http://www.google.com/search?q=123"
        
        guard let url = URLParser.parseURL(from: urlString) else {
            XCTFail("Failed to parse URL")
            return
        }
        
        let expected =
            URLParseSample.URL(scheme: "http", host: "www.google.com", path: "/search",
                               query: "q=123")
        
        XCTAssertEqual(url, expected)
        
        XCTAssertEqual(url.scheme, "http")
        XCTAssertEqual(url.host, "www.google.com")
        XCTAssertNil(url.port)
        XCTAssertEqual(url.path, "/search")
        XCTAssertEqual(url.query, "q=123")
        XCTAssertNil(url.fragment)
    }
    
    func testEdgeCases() {
        let urlString = "https://le-1.gov"
        guard let url = URLParser.parseURL(from: urlString) else {
            XCTFail("Failed to parse URL")
            return
        }
        
        let expected = URLParseSample.URL(scheme: "https", host: "le-1.gov")
        
        XCTAssertEqual(url, expected)
    }
    
    func testGeneratedURLs() {
        self.continueAfterFailure = false
        
        for urlString in testURLs {
            guard let url = URLParser.parseURL(from: urlString) else {
                XCTFail("Failed to parse valid URL: \(urlString)")
                return
            }
            
            // Test against Foundation's URL implementation
            let foundURL = Foundation.URL(string: urlString)!
            
            XCTAssertEqual(url.scheme, foundURL.scheme)
            XCTAssertEqual(url.user, foundURL.user)
            XCTAssertEqual(url.password, foundURL.password)
            XCTAssertEqual(url.host, foundURL.host)
            XCTAssertEqual(url.query, foundURL.query)
            //XCTAssertEqual(url.path ?? "", foundURL.path) // This still fails :C But URL is still valid.
            XCTAssertEqual(url.fragment, foundURL.fragment)
        }
    }
    
    func testParseIPV4() throws {
        let lexer = Lexer(input: "255.255.255.255")
        
        try XCTAssertEqual(lexer.consumeString { try $0.ipv4Address() }, "255.255.255.255")
        
        let lexerFail = Lexer(input: "255.255.255.256")
        
        XCTAssertThrowsError(try lexerFail.ipv4Address())
    }
    
    func testParsePath() throws {
        do {
            let lexer = Lexer(input: "/a//b/c")
            try XCTAssertEqual(lexer.consumeString { try $0.path() }, "/a//b/c")
        }
        
        do {
            let lexer = Lexer(input: "a//b/c")
            try XCTAssertEqual(lexer.consumeString { try $0.path() }, "a//b/c")
        }
        
        do {
            let lexer = Lexer(input: "//b/c") // path-absolute = "/" [ segment-nz *( "/" segment ) ]
            try XCTAssertEqual(lexer.consumeString { try $0.path() }, "/")
        }
    }
    
    func testParseURI() throws {
        do {
            let lexer = Lexer(input: "http://www.google.com")
            try XCTAssertEqual(lexer.URI(), "http://www.google.com")
        }
        
        do {
            let lexer = Lexer(input: "http://google")
            try XCTAssertEqual(lexer.URI(), "http://google")
        }
        
        do {
            let lexer = Lexer(input: "http://www.google.com/search?q=123#abc")
            try XCTAssertEqual(lexer.URI(), "http://www.google.com/search?q=123#abc")
        }
        
        do {
            let lexer = Lexer(input: "http://www.google.com:80/")
            try XCTAssertEqual(lexer.URI(), "http://www.google.com:80/")
        }
        
        do {
            let lexer = Lexer(input: "http://www.google.com:/")
            try XCTAssertEqual(lexer.URI(), "http://www.google.com:/")
        }
        
        do {
            let lexer = Lexer(input: "https://51.176.251.128:9/&@=/;/%ED/@#")
            try XCTAssertEqual(lexer.URI(), "https://51.176.251.128:9/&@=/;/%ED/@#")
        }
    }
    
    func testParseURIFull() {
        continueAfterFailure = false
        
        for url in testURLs {
            let lexer = Lexer(input: url)
            guard let parsedURI = try? lexer.URI() else {
                XCTFail("Failed to parse valid URL: \(url)")
                return
            }
            
            XCTAssertEqual(String(parsedURI), url)
        }
    }
    
    func testParseURIPerformance() {
        // Try running with optimizations on, too!
        measure {
            let multiURLs = repeatElement(testURLs, count: 10).flatMap { $0 }
            for url in multiURLs {
                let lexer = Lexer(input: url)
                _=try? lexer.URI()
            }
        }
    }
    
    func testParseURIPerformance_FoundationURL() {
        measure {
            let multiURLs = repeatElement(testURLs, count: 10).flatMap { $0 }
            for url in multiURLs {
                _=URL(string: url)
            }
        }
    }
}

let testURLs: [String] = [
    "HtTp://simplemachines.org/est/donec/odio/justo/sollicitudin.xml?tristique=mauris&in=non&tempus=ligula&sit=pellentesque&amet=ultrices&sem=phasellus&fusce=id&consequat=sapien&nulla=in&nisl=sapien&nunc=iaculis&nisl=congue&duis=vivamus&bibendum=metus&felis=arcu&sed=adipiscing&interdum=molestie&venenatis=hendrerit&turpis=at&enim=vulputate&blandit=vitae&mi=nisl&in=aenean&porttitor=lectus&pede=pellentesque&justo=eget&eu=nunc&massa=donec&donec=quis&dapibus=orci&duis=eget&at=orci&velit=vehicula&eu=condimentum&est=curabitur&congue=in&elementum=libero&in=ut&hac=massa&habitasse=volutpat&platea=convallis&dictumst=morbi&morbi=odio&vestibulum=odio&velit=elementum&id=eu&pretium=interdum",
    "https://pcworld.com/suspendisse/accumsan/tortor/quis/turpis.json?lectus=sapien&in=sapien&quam=non&fringilla=mi&rhoncus=integer&mauris=ac&enim=neque&leo=duis&rhoncus=bibendum&sed=morbi&vestibulum=non&sit=quam&amet=nec&cursus=dui&id=luctus&turpis=rutrum&integer=nulla&aliquet=tellus&massa=in&id=sagittis&lobortis=dui&convallis=vel&tortor=nisl&risus=duis",
    "https://joomla.org/ligula/in.jsp?sagittis=phasellus&nam=sit&congue=amet&risus=erat&semper=nulla&porta=tempus&volutpat=vivamus&quam=in&pede=felis&lobortis=eu&ligula=sapien&sit=cursus&amet=vestibulum&eleifend=proin&pede=eu&libero=mi&quis=nulla&orci=ac&nullam=enim&molestie=in&nibh=tempor&in=turpis&lectus=nec&pellentesque=euismod&at=scelerisque&nulla=quam&suspendisse=turpis&potenti=adipiscing&cras=lorem&in=vitae&purus=mattis&eu=nibh&magna=ligula&vulputate=nec&luctus=sem&cum=duis&sociis=aliquam&natoque=convallis&penatibus=nunc&et=proin&magnis=at&dis=turpis&parturient=a&montes=pede&nascetur=posuere&ridiculus=nonummy&mus=integer&vivamus=non&vestibulum=velit&sagittis=donec&sapien=diam&cum=neque&sociis=vestibulum&natoque=eget&penatibus=vulputate&et=ut&magnis=ultrices&dis=vel&parturient=augue&montes=vestibulum&nascetur=ante&ridiculus=ipsum&mus=primis&etiam=in&vel=faucibus&augue=orci&vestibulum=luctus&rutrum=et&rutrum=ultrices&neque=posuere&aenean=cubilia&auctor=curae&gravida=donec&sem=pharetra&praesent=magna&id=vestibulum&massa=aliquet&id=ultrices&nisl=erat&venenatis=tortor&lacinia=sollicitudin&aenean=mi&sit=sit&amet=amet&justo=lobortis&morbi=sapien&ut=sapien&odio=non&cras=mi&mi=integer&pede=ac&malesuada=neque",
    "http://pbs.org/risus/semper/porta/volutpat/quam/pede.aspx?varius=mattis&nulla=egestas&facilisi=metus&cras=aenean&non=fermentum&velit=donec&nec=ut&nisi=mauris&vulputate=eget&nonummy=massa&maecenas=tempor&tincidunt=convallis&lacus=nulla&at=neque&velit=libero&vivamus=convallis&vel=eget&nulla=eleifend&eget=luctus&eros=ultricies&elementum=eu&pellentesque=nibh&quisque=quisque&porta=id&volutpat=justo&erat=sit&quisque=amet&erat=sapien&eros=dignissim&viverra=vestibulum&eget=vestibulum&congue=ante&eget=ipsum&semper=primis&rutrum=in&nulla=faucibus&nunc=orci&purus=luctus&phasellus=et&in=ultrices&felis=posuere&donec=cubilia&semper=curae&sapien=nulla&a=dapibus&libero=dolor&nam=vel&dui=est&proin=donec&leo=odio&odio=justo&porttitor=sollicitudin&id=ut&consequat=suscipit&in=a&consequat=feugiat&ut=et&nulla=eros&sed=vestibulum&accumsan=ac&felis=est&ut=lacinia&at=nisi&dolor=venenatis&quis=tristique&odio=fusce&consequat=congue&varius=diam&integer=id&ac=ornare&leo=imperdiet&pellentesque=sapien&ultrices=urna&mattis=pretium&odio=nisl&donec=ut&vitae=volutpat&nisi=sapien&nam=arcu&ultrices=sed&libero=augue&non=aliquam&mattis=erat&pulvinar=volutpat&nulla=in&pede=congue&ullamcorper=etiam&augue=justo&a=etiam&suscipit=pretium",
    "https://list-manage.com/ultrices/erat.json?nibh=sit&quisque=amet&id=eros&justo=suspendisse&sit=accumsan&amet=tortor&sapien=quis",
    "https://webnode.com/habitasse.png?vivamus=vestibulum&tortor=sit&duis=amet&mattis=cursus&egestas=id&metus=turpis&aenean=integer&fermentum=aliquet&donec=massa&ut=id&mauris=lobortis&eget=convallis&massa=tortor&tempor=risus&convallis=dapibus&nulla=augue&neque=vel&libero=accumsan&convallis=tellus&eget=nisi&eleifend=eu&luctus=orci&ultricies=mauris&eu=lacinia&nibh=sapien&quisque=quis&id=libero&justo=nullam&sit=sit&amet=amet&sapien=turpis&dignissim=elementum&vestibulum=ligula&vestibulum=vehicula&ante=consequat&ipsum=morbi&primis=a&in=ipsum&faucibus=integer&orci=a&luctus=nibh&et=in&ultrices=quis&posuere=justo&cubilia=maecenas&curae=rhoncus&nulla=aliquam&dapibus=lacus&dolor=morbi&vel=quis&est=tortor&donec=id&odio=nulla&justo=ultrices&sollicitudin=aliquet&ut=maecenas&suscipit=leo&a=odio&feugiat=condimentum&et=id&eros=luctus&vestibulum=nec&ac=molestie&est=sed&lacinia=justo&nisi=pellentesque&venenatis=viverra&tristique=pede&fusce=ac&congue=diam&diam=cras&id=pellentesque&ornare=volutpat&imperdiet=dui&sapien=maecenas&urna=tristique&pretium=est&nisl=et&ut=tempus&volutpat=semper&sapien=est&arcu=quam&sed=pharetra&augue=magna&aliquam=ac&erat=consequat&volutpat=metus&in=sapien",
    "http://issuu.com/sagittis/nam/congue/risus/semper/porta.aspx?ante=odio&vel=porttitor&ipsum=id&praesent=consequat&blandit=in&lacinia=consequat&erat=ut&vestibulum=nulla&sed=sed&magna=accumsan&at=felis&nunc=ut&commodo=at&placerat=dolor&praesent=quis&blandit=odio&nam=consequat&nulla=varius&integer=integer&pede=ac&justo=leo&lacinia=pellentesque&eget=ultrices&tincidunt=mattis&eget=odio&tempus=donec&vel=vitae&pede=nisi&morbi=nam&porttitor=ultrices",
    "https://patch.com/sed/tristique.jpg?habitasse=scelerisque&platea=quam&dictumst=turpis&maecenas=adipiscing&ut=lorem&massa=vitae&quis=mattis&augue=nibh&luctus=ligula&tincidunt=nec&nulla=sem&mollis=duis&molestie=aliquam&lorem=convallis&quisque=nunc&ut=proin&erat=at&curabitur=turpis&gravida=a&nisi=pede&at=posuere&nibh=nonummy&in=integer&hac=non&habitasse=velit&platea=donec&dictumst=diam&aliquam=neque&augue=vestibulum&quam=eget&sollicitudin=vulputate&vitae=ut&consectetuer=ultrices&eget=vel&rutrum=augue&at=vestibulum&lorem=ante&integer=ipsum&tincidunt=primis&ante=in&vel=faucibus&ipsum=orci&praesent=luctus&blandit=et&lacinia=ultrices&erat=posuere&vestibulum=cubilia&sed=curae&magna=donec&at=pharetra&nunc=magna&commodo=vestibulum&placerat=aliquet&praesent=ultrices&blandit=erat&nam=tortor&nulla=sollicitudin&integer=mi&pede=sit&justo=amet&lacinia=lobortis&eget=sapien",
    "https://opensource.org/felis/eu/sapien/cursus.jpg?auctor=mi&sed=nulla&tristique=ac&in=enim&tempus=in&sit=tempor&amet=turpis&sem=nec&fusce=euismod&consequat=scelerisque&nulla=quam&nisl=turpis&nunc=adipiscing&nisl=lorem&duis=vitae&bibendum=mattis&felis=nibh&sed=ligula&interdum=nec&venenatis=sem&turpis=duis&enim=aliquam&blandit=convallis&mi=nunc&in=proin&porttitor=at&pede=turpis&justo=a&eu=pede&massa=posuere&donec=nonummy&dapibus=integer&duis=non&at=velit&velit=donec&eu=diam&est=neque&congue=vestibulum&elementum=eget&in=vulputate&hac=ut&habitasse=ultrices&platea=vel&dictumst=augue&morbi=vestibulum&vestibulum=ante&velit=ipsum&id=primis&pretium=in&iaculis=faucibus&diam=orci&erat=luctus&fermentum=et&justo=ultrices&nec=posuere&condimentum=cubilia&neque=curae&sapien=donec&placerat=pharetra&ante=magna&nulla=vestibulum&justo=aliquet&aliquam=ultrices&quis=erat&turpis=tortor&eget=sollicitudin&elit=mi&sodales=sit&scelerisque=amet&mauris=lobortis&sit=sapien&amet=sapien&eros=non&suspendisse=mi&accumsan=integer&tortor=ac&quis=neque&turpis=duis&sed=bibendum&ante=morbi&vivamus=non&tortor=quam&duis=nec&mattis=dui&egestas=luctus&metus=rutrum&aenean=nulla&fermentum=tellus&donec=in&ut=sagittis&mauris=dui&eget=vel&massa=nisl&tempor=duis&convallis=ac&nulla=nibh&neque=fusce",
    "https://ifeng.com/ornare/imperdiet/sapien/urna.json?nullam=imperdiet&varius=sapien&nulla=urna&facilisi=pretium&cras=nisl&non=ut&velit=volutpat&nec=sapien&nisi=arcu&vulputate=sed&nonummy=augue&maecenas=aliquam&tincidunt=erat&lacus=volutpat&at=in&velit=congue&vivamus=etiam&vel=justo&nulla=etiam&eget=pretium&eros=iaculis&elementum=justo&pellentesque=in&quisque=hac&porta=habitasse&volutpat=platea&erat=dictumst&quisque=etiam&erat=faucibus&eros=cursus&viverra=urna&eget=ut&congue=tellus&eget=nulla&semper=ut&rutrum=erat&nulla=id&nunc=mauris&purus=vulputate&phasellus=elementum&in=nullam&felis=varius&donec=nulla&semper=facilisi&sapien=cras&a=non&libero=velit&nam=nec&dui=nisi&proin=vulputate&leo=nonummy&odio=maecenas&porttitor=tincidunt&id=lacus&consequat=at&in=velit&consequat=vivamus&ut=vel",
    "https://imdb.com/in/imperdiet/et/commodo/vulputate/justo.jpg?luctus=lorem&et=ipsum&ultrices=dolor&posuere=sit&cubilia=amet&curae=consectetuer&mauris=adipiscing&viverra=elit&diam=proin&vitae=interdum&quam=mauris&suspendisse=non&potenti=ligula&nullam=pellentesque&porttitor=ultrices&lacus=phasellus&at=id&turpis=sapien&donec=in&posuere=sapien&metus=iaculis&vitae=congue",
    "https://spiegel.de/integer/non.json?tristique=integer&in=aliquet&tempus=massa&sit=id&amet=lobortis&sem=convallis&fusce=tortor&consequat=risus&nulla=dapibus&nisl=augue&nunc=vel&nisl=accumsan&duis=tellus&bibendum=nisi&felis=eu",
    "http://nature.com/ultricies/eu/nibh/quisque/id/justo/sit.js?dis=etiam&parturient=faucibus&montes=cursus&nascetur=urna&ridiculus=ut&mus=tellus&vivamus=nulla&vestibulum=ut&sagittis=erat&sapien=id&cum=mauris&sociis=vulputate&natoque=elementum&penatibus=nullam&et=varius&magnis=nulla&dis=facilisi&parturient=cras&montes=non&nascetur=velit&ridiculus=nec&mus=nisi&etiam=vulputate&vel=nonummy&augue=maecenas&vestibulum=tincidunt&rutrum=lacus&rutrum=at&neque=velit&aenean=vivamus&auctor=vel&gravida=nulla&sem=eget&praesent=eros&id=elementum&massa=pellentesque&id=quisque&nisl=porta&venenatis=volutpat&lacinia=erat&aenean=quisque&sit=erat&amet=eros&justo=viverra&morbi=eget&ut=congue&odio=eget&cras=semper&mi=rutrum&pede=nulla&malesuada=nunc&in=purus&imperdiet=phasellus&et=in&commodo=felis&vulputate=donec&justo=semper&in=sapien&blandit=a&ultrices=libero&enim=nam&lorem=dui&ipsum=proin&dolor=leo&sit=odio&amet=porttitor&consectetuer=id&adipiscing=consequat&elit=in&proin=consequat&interdum=ut&mauris=nulla&non=sed&ligula=accumsan&pellentesque=felis&ultrices=ut&phasellus=at&id=dolor&sapien=quis&in=odio&sapien=consequat&iaculis=varius&congue=integer&vivamus=ac&metus=leo&arcu=pellentesque",
    "http://columbia.edu/suspendisse/potenti/cras/in/purus.js?consequat=phasellus&nulla=id&nisl=sapien&nunc=in&nisl=sapien&duis=iaculis&bibendum=congue&felis=vivamus&sed=metus&interdum=arcu&venenatis=adipiscing&turpis=molestie&enim=hendrerit&blandit=at&mi=vulputate&in=vitae&porttitor=nisl&pede=aenean&justo=lectus&eu=pellentesque&massa=eget&donec=nunc&dapibus=donec&duis=quis&at=orci&velit=eget&eu=orci&est=vehicula&congue=condimentum&elementum=curabitur&in=in&hac=libero&habitasse=ut&platea=massa&dictumst=volutpat&morbi=convallis&vestibulum=morbi&velit=odio&id=odio&pretium=elementum&iaculis=eu&diam=interdum&erat=eu&fermentum=tincidunt&justo=in&nec=leo&condimentum=maecenas&neque=pulvinar&sapien=lobortis&placerat=est&ante=phasellus&nulla=sit&justo=amet&aliquam=erat&quis=nulla&turpis=tempus&eget=vivamus&elit=in&sodales=felis&scelerisque=eu&mauris=sapien&sit=cursus&amet=vestibulum&eros=proin&suspendisse=eu&accumsan=mi&tortor=nulla&quis=ac&turpis=enim&sed=in&ante=tempor",
    "https://jigsy.com/eu/magna/vulputate/luctus/cum/sociis.jpg?leo=curabitur&rhoncus=in&sed=libero&vestibulum=ut&sit=massa&amet=volutpat&cursus=convallis&id=morbi&turpis=odio&integer=odio&aliquet=elementum",
    "http://bing.com/velit/eu/est/congue.json?lectus=pellentesque&pellentesque=eget&eget=nunc&nunc=donec&donec=quis&quis=orci&orci=eget&eget=orci&orci=vehicula&vehicula=condimentum&condimentum=curabitur&curabitur=in&in=libero&libero=ut&ut=massa&massa=volutpat&volutpat=convallis&convallis=morbi&morbi=odio&odio=odio&odio=elementum&elementum=eu&eu=interdum&interdum=eu&eu=tincidunt&tincidunt=in&in=leo&leo=maecenas&maecenas=pulvinar&pulvinar=lobortis&lobortis=est&est=phasellus&phasellus=sit&sit=amet&amet=erat&erat=nulla&nulla=tempus&tempus=vivamus&vivamus=in&in=felis&felis=eu&eu=sapien&sapien=cursus&cursus=vestibulum&vestibulum=proin&proin=eu&eu=mi&mi=nulla&nulla=ac&ac=enim&enim=in&in=tempor&tempor=turpis&turpis=nec&nec=euismod&euismod=scelerisque&scelerisque=quam&quam=turpis&turpis=adipiscing&adipiscing=lorem&lorem=vitae&vitae=mattis&mattis=nibh&nibh=ligula&ligula=nec&nec=sem",
    "http://hp.com/elementum/nullam.aspx?magna=ante&vestibulum=vel&aliquet=ipsum&ultrices=praesent&erat=blandit&tortor=lacinia&sollicitudin=erat&mi=vestibulum&sit=sed&amet=magna&lobortis=at&sapien=nunc&sapien=commodo&non=placerat&mi=praesent&integer=blandit&ac=nam&neque=nulla&duis=integer&bibendum=pede&morbi=justo&non=lacinia&quam=eget&nec=tincidunt&dui=eget&luctus=tempus&rutrum=vel&nulla=pede&tellus=morbi&in=porttitor&sagittis=lorem&dui=id",
    "https://mac.com/semper/est/quam/pharetra.png?primis=semper&in=rutrum&faucibus=nulla&orci=nunc&luctus=purus&et=phasellus&ultrices=in&posuere=felis&cubilia=donec&curae=semper&duis=sapien&faucibus=a&accumsan=libero&odio=nam&curabitur=dui&convallis=proin&duis=leo&consequat=odio&dui=porttitor&nec=id&nisi=consequat&volutpat=in&eleifend=consequat&donec=ut&ut=nulla&dolor=sed",
    "http://feedburner.com/non/pretium/quis/lectus/suspendisse.json?amet=porttitor&consectetuer=pede&adipiscing=justo&elit=eu&proin=massa&interdum=donec&mauris=dapibus&non=duis&ligula=at&pellentesque=velit&ultrices=eu&phasellus=est&id=congue&sapien=elementum&in=in&sapien=hac&iaculis=habitasse&congue=platea&vivamus=dictumst&metus=morbi&arcu=vestibulum&adipiscing=velit&molestie=id&hendrerit=pretium&at=iaculis&vulputate=diam&vitae=erat&nisl=fermentum&aenean=justo&lectus=nec&pellentesque=condimentum&eget=neque&nunc=sapien&donec=placerat&quis=ante&orci=nulla&eget=justo&orci=aliquam&vehicula=quis&condimentum=turpis&curabitur=eget&in=elit&libero=sodales&ut=scelerisque&massa=mauris&volutpat=sit&convallis=amet&morbi=eros&odio=suspendisse&odio=accumsan&elementum=tortor&eu=quis&interdum=turpis&eu=sed&tincidunt=ante&in=vivamus&leo=tortor&maecenas=duis",
    "https://businessinsider.com/placerat/praesent/blandit/nam.js?est=volutpat&lacinia=convallis&nisi=morbi&venenatis=odio&tristique=odio&fusce=elementum&congue=eu&diam=interdum&id=eu&ornare=tincidunt&imperdiet=in&sapien=leo&urna=maecenas&pretium=pulvinar&nisl=lobortis&ut=est&volutpat=phasellus&sapien=sit&arcu=amet&sed=erat&augue=nulla&aliquam=tempus&erat=vivamus&volutpat=in&in=felis&congue=eu&etiam=sapien&justo=cursus&etiam=vestibulum&pretium=proin&iaculis=eu&justo=mi&in=nulla&hac=ac&habitasse=enim&platea=in&dictumst=tempor&etiam=turpis&faucibus=nec&cursus=euismod",
    "http://baidu.com/luctus/ultricies.jsp?amet=consectetuer&sapien=adipiscing&dignissim=elit&vestibulum=proin&vestibulum=interdum&ante=mauris&ipsum=non&primis=ligula&in=pellentesque&faucibus=ultrices&orci=phasellus&luctus=id&et=sapien&ultrices=in&posuere=sapien&cubilia=iaculis&curae=congue&nulla=vivamus&dapibus=metus&dolor=arcu&vel=adipiscing&est=molestie&donec=hendrerit&odio=at&justo=vulputate&sollicitudin=vitae&ut=nisl&suscipit=aenean&a=lectus&feugiat=pellentesque&et=eget&eros=nunc&vestibulum=donec&ac=quis&est=orci&lacinia=eget&nisi=orci&venenatis=vehicula&tristique=condimentum&fusce=curabitur&congue=in&diam=libero&id=ut&ornare=massa&imperdiet=volutpat&sapien=convallis&urna=morbi&pretium=odio&nisl=odio&ut=elementum&volutpat=eu&sapien=interdum&arcu=eu&sed=tincidunt&augue=in&aliquam=leo&erat=maecenas&volutpat=pulvinar&in=lobortis&congue=est&etiam=phasellus&justo=sit&etiam=amet&pretium=erat&iaculis=nulla&justo=tempus&in=vivamus&hac=in&habitasse=felis&platea=eu&dictumst=sapien&etiam=cursus&faucibus=vestibulum",
    "https://mail.ru/ut/at/dolor/quis/odio/consequat.js?felis=velit&sed=nec&interdum=nisi&venenatis=vulputate&turpis=nonummy&enim=maecenas&blandit=tincidunt&mi=lacus&in=at&porttitor=velit&pede=vivamus&justo=vel&eu=nulla&massa=eget&donec=eros&dapibus=elementum&duis=pellentesque&at=quisque&velit=porta&eu=volutpat&est=erat&congue=quisque&elementum=erat&in=eros&hac=viverra&habitasse=eget&platea=congue&dictumst=eget&morbi=semper&vestibulum=rutrum&velit=nulla&id=nunc&pretium=purus",
    "http://accuweather.com/maecenas/tristique/est/et/tempus/semper/est.png?montes=in&nascetur=quis&ridiculus=justo&mus=maecenas&vivamus=rhoncus&vestibulum=aliquam&sagittis=lacus&sapien=morbi&cum=quis&sociis=tortor&natoque=id&penatibus=nulla&et=ultrices&magnis=aliquet&dis=maecenas&parturient=leo&montes=odio&nascetur=condimentum&ridiculus=id&mus=luctus&etiam=nec&vel=molestie&augue=sed&vestibulum=justo&rutrum=pellentesque&rutrum=viverra&neque=pede&aenean=ac&auctor=diam&gravida=cras&sem=pellentesque&praesent=volutpat&id=dui&massa=maecenas&id=tristique&nisl=est&venenatis=et&lacinia=tempus&aenean=semper&sit=est&amet=quam&justo=pharetra&morbi=magna&ut=ac&odio=consequat&cras=metus&mi=sapien&pede=ut&malesuada=nunc&in=vestibulum&imperdiet=ante&et=ipsum&commodo=primis&vulputate=in&justo=faucibus",
    "http://flavors.me/pede/malesuada/in/imperdiet/et/commodo/vulputate.aspx?ut=id&rhoncus=nulla&aliquet=ultrices&pulvinar=aliquet&sed=maecenas&nisl=leo&nunc=odio&rhoncus=condimentum&dui=id&vel=luctus&sem=nec&sed=molestie&sagittis=sed&nam=justo&congue=pellentesque&risus=viverra&semper=pede&porta=ac&volutpat=diam&quam=cras&pede=pellentesque&lobortis=volutpat&ligula=dui&sit=maecenas&amet=tristique&eleifend=est&pede=et&libero=tempus&quis=semper&orci=est&nullam=quam&molestie=pharetra&nibh=magna&in=ac&lectus=consequat&pellentesque=metus&at=sapien&nulla=ut&suspendisse=nunc&potenti=vestibulum&cras=ante&in=ipsum&purus=primis&eu=in&magna=faucibus&vulputate=orci&luctus=luctus&cum=et&sociis=ultrices&natoque=posuere&penatibus=cubilia&et=curae&magnis=mauris&dis=viverra&parturient=diam&montes=vitae&nascetur=quam&ridiculus=suspendisse&mus=potenti&vivamus=nullam&vestibulum=porttitor&sagittis=lacus&sapien=at&cum=turpis&sociis=donec&natoque=posuere&penatibus=metus&et=vitae&magnis=ipsum&dis=aliquam&parturient=non&montes=mauris&nascetur=morbi&ridiculus=non&mus=lectus&etiam=aliquam&vel=sit&augue=amet&vestibulum=diam&rutrum=in&rutrum=magna&neque=bibendum&aenean=imperdiet&auctor=nullam&gravida=orci&sem=pede&praesent=venenatis&id=non&massa=sodales&id=sed&nisl=tincidunt",
    "http://cyberchimps.com/eleifend/quam.png?vel=ipsum&est=primis&donec=in&odio=faucibus&justo=orci&sollicitudin=luctus&ut=et&suscipit=ultrices&a=posuere&feugiat=cubilia&et=curae&eros=donec&vestibulum=pharetra&ac=magna&est=vestibulum&lacinia=aliquet&nisi=ultrices&venenatis=erat&tristique=tortor&fusce=sollicitudin&congue=mi&diam=sit&id=amet&ornare=lobortis&imperdiet=sapien&sapien=sapien&urna=non&pretium=mi&nisl=integer&ut=ac&volutpat=neque&sapien=duis&arcu=bibendum&sed=morbi&augue=non&aliquam=quam&erat=nec&volutpat=dui&in=luctus&congue=rutrum&etiam=nulla&justo=tellus&etiam=in&pretium=sagittis&iaculis=dui&justo=vel&in=nisl&hac=duis&habitasse=ac&platea=nibh&dictumst=fusce&etiam=lacus&faucibus=purus&cursus=aliquet&urna=at&ut=feugiat&tellus=non&nulla=pretium&ut=quis&erat=lectus&id=suspendisse&mauris=potenti&vulputate=in&elementum=eleifend&nullam=quam&varius=a&nulla=odio&facilisi=in&cras=hac&non=habitasse&velit=platea&nec=dictumst&nisi=maecenas&vulputate=ut&nonummy=massa&maecenas=quis&tincidunt=augue&lacus=luctus&at=tincidunt&velit=nulla&vivamus=mollis&vel=molestie&nulla=lorem&eget=quisque&eros=ut&elementum=erat&pellentesque=curabitur&quisque=gravida&porta=nisi&volutpat=at&erat=nibh&quisque=in&erat=hac&eros=habitasse",
    "http://altervista.org/justo/aliquam/quis.aspx?curae=lectus&nulla=in&dapibus=quam&dolor=fringilla&vel=rhoncus&est=mauris&donec=enim&odio=leo&justo=rhoncus&sollicitudin=sed&ut=vestibulum&suscipit=sit&a=amet&feugiat=cursus&et=id&eros=turpis&vestibulum=integer&ac=aliquet&est=massa&lacinia=id&nisi=lobortis&venenatis=convallis&tristique=tortor&fusce=risus&congue=dapibus&diam=augue&id=vel&ornare=accumsan&imperdiet=tellus&sapien=nisi&urna=eu&pretium=orci&nisl=mauris&ut=lacinia&volutpat=sapien&sapien=quis&arcu=libero&sed=nullam&augue=sit&aliquam=amet&erat=turpis&volutpat=elementum&in=ligula&congue=vehicula&etiam=consequat&justo=morbi&etiam=a&pretium=ipsum&iaculis=integer&justo=a&in=nibh&hac=in&habitasse=quis&platea=justo&dictumst=maecenas&etiam=rhoncus&faucibus=aliquam&cursus=lacus&urna=morbi&ut=quis&tellus=tortor&nulla=id&ut=nulla&erat=ultrices&id=aliquet&mauris=maecenas&vulputate=leo&elementum=odio&nullam=condimentum&varius=id&nulla=luctus&facilisi=nec&cras=molestie&non=sed&velit=justo&nec=pellentesque&nisi=viverra&vulputate=pede&nonummy=ac&maecenas=diam&tincidunt=cras&lacus=pellentesque&at=volutpat&velit=dui&vivamus=maecenas&vel=tristique&nulla=est&eget=et&eros=tempus&elementum=semper&pellentesque=est&quisque=quam&porta=pharetra&volutpat=magna&erat=ac",
    "https://intel.com/molestie/nibh/in/lectus.xml?lacus=sapien&morbi=placerat&quis=ante&tortor=nulla&id=justo&nulla=aliquam&ultrices=quis&aliquet=turpis&maecenas=eget&leo=elit&odio=sodales&condimentum=scelerisque&id=mauris&luctus=sit&nec=amet&molestie=eros&sed=suspendisse&justo=accumsan&pellentesque=tortor&viverra=quis&pede=turpis&ac=sed&diam=ante&cras=vivamus&pellentesque=tortor&volutpat=duis&dui=mattis&maecenas=egestas&tristique=metus",
    "http://opera.com/consectetuer/adipiscing/elit/proin.jsp?mauris=ultrices&lacinia=posuere&sapien=cubilia&quis=curae&libero=mauris&nullam=viverra&sit=diam&amet=vitae&turpis=quam&elementum=suspendisse&ligula=potenti&vehicula=nullam&consequat=porttitor&morbi=lacus",
    "https://ning.com/mus/etiam/vel/augue/vestibulum.aspx?nec=ridiculus&euismod=mus&scelerisque=etiam&quam=vel&turpis=augue&adipiscing=vestibulum&lorem=rutrum&vitae=rutrum&mattis=neque&nibh=aenean&ligula=auctor&nec=gravida&sem=sem&duis=praesent&aliquam=id&convallis=massa&nunc=id&proin=nisl&at=venenatis&turpis=lacinia&a=aenean&pede=sit&posuere=amet&nonummy=justo&integer=morbi&non=ut&velit=odio&donec=cras&diam=mi&neque=pede&vestibulum=malesuada&eget=in&vulputate=imperdiet&ut=et&ultrices=commodo&vel=vulputate&augue=justo&vestibulum=in&ante=blandit&ipsum=ultrices&primis=enim&in=lorem&faucibus=ipsum&orci=dolor&luctus=sit&et=amet&ultrices=consectetuer&posuere=adipiscing&cubilia=elit&curae=proin&donec=interdum&pharetra=mauris&magna=non&vestibulum=ligula&aliquet=pellentesque&ultrices=ultrices&erat=phasellus&tortor=id&sollicitudin=sapien&mi=in&sit=sapien&amet=iaculis&lobortis=congue&sapien=vivamus&sapien=metus&non=arcu&mi=adipiscing&integer=molestie&ac=hendrerit&neque=at&duis=vulputate&bibendum=vitae&morbi=nisl&non=aenean&quam=lectus&nec=pellentesque&dui=eget&luctus=nunc&rutrum=donec&nulla=quis&tellus=orci&in=eget&sagittis=orci&dui=vehicula&vel=condimentum&nisl=curabitur&duis=in&ac=libero&nibh=ut",
    "http://toplist.cz/pellentesque/quisque/porta/volutpat/erat/quisque/erat.jsp?in=adipiscing&sapien=elit&iaculis=proin&congue=interdum&vivamus=mauris&metus=non&arcu=ligula&adipiscing=pellentesque&molestie=ultrices&hendrerit=phasellus&at=id&vulputate=sapien&vitae=in&nisl=sapien&aenean=iaculis&lectus=congue&pellentesque=vivamus&eget=metus&nunc=arcu&donec=adipiscing&quis=molestie&orci=hendrerit&eget=at&orci=vulputate&vehicula=vitae&condimentum=nisl&curabitur=aenean&in=lectus&libero=pellentesque&ut=eget&massa=nunc&volutpat=donec&convallis=quis&morbi=orci&odio=eget&odio=orci&elementum=vehicula&eu=condimentum&interdum=curabitur&eu=in&tincidunt=libero&in=ut&leo=massa&maecenas=volutpat&pulvinar=convallis&lobortis=morbi&est=odio&phasellus=odio&sit=elementum&amet=eu&erat=interdum",
    "https://stanford.edu/orci/luctus/et/ultrices/posuere.jpg?sollicitudin=cum&vitae=sociis&consectetuer=natoque&eget=penatibus&rutrum=et&at=magnis&lorem=dis&integer=parturient&tincidunt=montes&ante=nascetur&vel=ridiculus&ipsum=mus&praesent=etiam&blandit=vel&lacinia=augue&erat=vestibulum&vestibulum=rutrum&sed=rutrum&magna=neque&at=aenean&nunc=auctor&commodo=gravida&placerat=sem&praesent=praesent&blandit=id&nam=massa&nulla=id&integer=nisl&pede=venenatis&justo=lacinia&lacinia=aenean&eget=sit&tincidunt=amet&eget=justo",
    "http://nationalgeographic.com/sapien/ut/nunc/vestibulum.aspx?elit=non&ac=mauris&nulla=morbi&sed=non&vel=lectus&enim=aliquam&sit=sit&amet=amet&nunc=diam&viverra=in&dapibus=magna&nulla=bibendum&suscipit=imperdiet&ligula=nullam",
    "https://diigo.com/consectetuer/adipiscing.jpg?ultrices=iaculis&vel=justo&augue=in&vestibulum=hac&ante=habitasse&ipsum=platea&primis=dictumst&in=etiam&faucibus=faucibus&orci=cursus&luctus=urna&et=ut&ultrices=tellus&posuere=nulla&cubilia=ut&curae=erat&donec=id&pharetra=mauris&magna=vulputate&vestibulum=elementum&aliquet=nullam&ultrices=varius&erat=nulla&tortor=facilisi&sollicitudin=cras&mi=non&sit=velit&amet=nec&lobortis=nisi&sapien=vulputate&sapien=nonummy&non=maecenas&mi=tincidunt&integer=lacus&ac=at&neque=velit&duis=vivamus&bibendum=vel&morbi=nulla&non=eget&quam=eros&nec=elementum&dui=pellentesque&luctus=quisque&rutrum=porta&nulla=volutpat&tellus=erat&in=quisque&sagittis=erat&dui=eros&vel=viverra&nisl=eget&duis=congue&ac=eget&nibh=semper&fusce=rutrum&lacus=nulla&purus=nunc&aliquet=purus&at=phasellus&feugiat=in&non=felis&pretium=donec&quis=semper&lectus=sapien&suspendisse=a&potenti=libero&in=nam&eleifend=dui&quam=proin&a=leo&odio=odio&in=porttitor&hac=id&habitasse=consequat&platea=in&dictumst=consequat&maecenas=ut&ut=nulla&massa=sed&quis=accumsan&augue=felis&luctus=ut&tincidunt=at&nulla=dolor&mollis=quis",
    "http://feedburner.com/orci.xml?nam=donec&dui=diam&proin=neque&leo=vestibulum&odio=eget&porttitor=vulputate&id=ut&consequat=ultrices&in=vel&consequat=augue&ut=vestibulum&nulla=ante&sed=ipsum&accumsan=primis&felis=in&ut=faucibus&at=orci&dolor=luctus&quis=et&odio=ultrices&consequat=posuere&varius=cubilia&integer=curae&ac=donec&leo=pharetra&pellentesque=magna&ultrices=vestibulum&mattis=aliquet&odio=ultrices&donec=erat&vitae=tortor&nisi=sollicitudin&nam=mi&ultrices=sit&libero=amet&non=lobortis&mattis=sapien&pulvinar=sapien&nulla=non&pede=mi&ullamcorper=integer&augue=ac&a=neque&suscipit=duis&nulla=bibendum&elit=morbi&ac=non&nulla=quam&sed=nec&vel=dui&enim=luctus&sit=rutrum&amet=nulla&nunc=tellus&viverra=in&dapibus=sagittis&nulla=dui&suscipit=vel&ligula=nisl&in=duis&lacus=ac&curabitur=nibh&at=fusce&ipsum=lacus&ac=purus&tellus=aliquet&semper=at&interdum=feugiat&mauris=non&ullamcorper=pretium&purus=quis&sit=lectus&amet=suspendisse&nulla=potenti&quisque=in&arcu=eleifend&libero=quam&rutrum=a&ac=odio&lobortis=in&vel=hac&dapibus=habitasse&at=platea&diam=dictumst&nam=maecenas",
    "http://51.la/odio/donec.js?blandit=luctus&nam=nec&nulla=molestie&integer=sed&pede=justo&justo=pellentesque&lacinia=viverra&eget=pede&tincidunt=ac&eget=diam&tempus=cras&vel=pellentesque&pede=volutpat&morbi=dui&porttitor=maecenas&lorem=tristique&id=est&ligula=et&suspendisse=tempus&ornare=semper&consequat=est&lectus=quam&in=pharetra&est=magna&risus=ac&auctor=consequat&sed=metus&tristique=sapien&in=ut",
    "http://arstechnica.com/lacus/morbi.jpg?vestibulum=eu&ante=est&ipsum=congue&primis=elementum&in=in&faucibus=hac&orci=habitasse&luctus=platea&et=dictumst&ultrices=morbi&posuere=vestibulum&cubilia=velit&curae=id&donec=pretium&pharetra=iaculis&magna=diam&vestibulum=erat&aliquet=fermentum",
    "https://dailymail.co.uk/nullam/orci/pede.png?sed=vitae&justo=mattis&pellentesque=nibh&viverra=ligula",
    "https://creativecommons.org/in.aspx?volutpat=ipsum&erat=primis&quisque=in&erat=faucibus&eros=orci&viverra=luctus&eget=et&congue=ultrices&eget=posuere&semper=cubilia&rutrum=curae&nulla=donec&nunc=pharetra&purus=magna&phasellus=vestibulum&in=aliquet&felis=ultrices&donec=erat&semper=tortor&sapien=sollicitudin&a=mi&libero=sit&nam=amet&dui=lobortis&proin=sapien&leo=sapien&odio=non&porttitor=mi&id=integer&consequat=ac&in=neque&consequat=duis&ut=bibendum&nulla=morbi&sed=non&accumsan=quam&felis=nec&ut=dui&at=luctus",
    "http://dailymail.co.uk/tempus/sit/amet/sem/fusce/consequat.jpg?id=tincidunt&massa=in&id=leo&nisl=maecenas&venenatis=pulvinar&lacinia=lobortis&aenean=est&sit=phasellus&amet=sit&justo=amet&morbi=erat&ut=nulla&odio=tempus&cras=vivamus&mi=in&pede=felis&malesuada=eu&in=sapien&imperdiet=cursus&et=vestibulum&commodo=proin&vulputate=eu&justo=mi&in=nulla&blandit=ac&ultrices=enim&enim=in&lorem=tempor&ipsum=turpis&dolor=nec&sit=euismod&amet=scelerisque&consectetuer=quam&adipiscing=turpis&elit=adipiscing&proin=lorem&interdum=vitae&mauris=mattis&non=nibh&ligula=ligula&pellentesque=nec&ultrices=sem&phasellus=duis&id=aliquam&sapien=convallis&in=nunc&sapien=proin&iaculis=at&congue=turpis&vivamus=a&metus=pede&arcu=posuere&adipiscing=nonummy&molestie=integer&hendrerit=non&at=velit&vulputate=donec&vitae=diam&nisl=neque&aenean=vestibulum&lectus=eget&pellentesque=vulputate&eget=ut&nunc=ultrices&donec=vel&quis=augue&orci=vestibulum&eget=ante&orci=ipsum&vehicula=primis&condimentum=in&curabitur=faucibus&in=orci&libero=luctus&ut=et&massa=ultrices&volutpat=posuere&convallis=cubilia&morbi=curae&odio=donec&odio=pharetra&elementum=magna&eu=vestibulum&interdum=aliquet&eu=ultrices&tincidunt=erat&in=tortor&leo=sollicitudin&maecenas=mi&pulvinar=sit&lobortis=amet&est=lobortis&phasellus=sapien&sit=sapien&amet=non&erat=mi&nulla=integer&tempus=ac&vivamus=neque",
    "http://posterous.com/gravida/sem.js?vestibulum=nec&rutrum=dui&rutrum=luctus&neque=rutrum&aenean=nulla&auctor=tellus&gravida=in&sem=sagittis&praesent=dui&id=vel&massa=nisl&id=duis&nisl=ac&venenatis=nibh&lacinia=fusce&aenean=lacus&sit=purus&amet=aliquet&justo=at&morbi=feugiat&ut=non&odio=pretium&cras=quis&mi=lectus&pede=suspendisse&malesuada=potenti&in=in&imperdiet=eleifend&et=quam&commodo=a&vulputate=odio&justo=in&in=hac&blandit=habitasse&ultrices=platea&enim=dictumst&lorem=maecenas&ipsum=ut&dolor=massa&sit=quis&amet=augue&consectetuer=luctus&adipiscing=tincidunt&elit=nulla&proin=mollis&interdum=molestie&mauris=lorem&non=quisque&ligula=ut&pellentesque=erat&ultrices=curabitur&phasellus=gravida&id=nisi&sapien=at&in=nibh&sapien=in&iaculis=hac&congue=habitasse&vivamus=platea&metus=dictumst&arcu=aliquam&adipiscing=augue&molestie=quam&hendrerit=sollicitudin&at=vitae&vulputate=consectetuer&vitae=eget&nisl=rutrum&aenean=at&lectus=lorem&pellentesque=integer&eget=tincidunt&nunc=ante&donec=vel",
    "http://vimeo.com/libero.jsp?erat=ut&eros=nunc&viverra=vestibulum&eget=ante&congue=ipsum&eget=primis&semper=in&rutrum=faucibus&nulla=orci&nunc=luctus&purus=et&phasellus=ultrices&in=posuere&felis=cubilia&donec=curae&semper=mauris&sapien=viverra&a=diam&libero=vitae&nam=quam&dui=suspendisse&proin=potenti&leo=nullam&odio=porttitor&porttitor=lacus&id=at&consequat=turpis&in=donec&consequat=posuere&ut=metus",
    "https://miibeian.gov.cn/potenti/in/eleifend/quam.aspx?nulla=quis&neque=tortor&libero=id&convallis=nulla&eget=ultrices&eleifend=aliquet&luctus=maecenas&ultricies=leo&eu=odio&nibh=condimentum&quisque=id&id=luctus&justo=nec&sit=molestie&amet=sed&sapien=justo&dignissim=pellentesque&vestibulum=viverra&vestibulum=pede&ante=ac&ipsum=diam&primis=cras&in=pellentesque&faucibus=volutpat&orci=dui&luctus=maecenas&et=tristique&ultrices=est&posuere=et&cubilia=tempus&curae=semper&nulla=est&dapibus=quam&dolor=pharetra&vel=magna&est=ac&donec=consequat&odio=metus&justo=sapien&sollicitudin=ut&ut=nunc&suscipit=vestibulum&a=ante&feugiat=ipsum&et=primis&eros=in&vestibulum=faucibus&ac=orci&est=luctus&lacinia=et&nisi=ultrices&venenatis=posuere",
    "http://google.ru/tristique/fusce.aspx?ipsum=vestibulum&dolor=vestibulum&sit=ante&amet=ipsum&consectetuer=primis&adipiscing=in&elit=faucibus&proin=orci&interdum=luctus&mauris=et&non=ultrices&ligula=posuere&pellentesque=cubilia&ultrices=curae&phasellus=nulla&id=dapibus&sapien=dolor&in=vel&sapien=est&iaculis=donec&congue=odio&vivamus=justo&metus=sollicitudin&arcu=ut&adipiscing=suscipit&molestie=a&hendrerit=feugiat&at=et&vulputate=eros&vitae=vestibulum&nisl=ac&aenean=est&lectus=lacinia&pellentesque=nisi&eget=venenatis&nunc=tristique&donec=fusce&quis=congue&orci=diam&eget=id&orci=ornare&vehicula=imperdiet&condimentum=sapien&curabitur=urna&in=pretium&libero=nisl&ut=ut&massa=volutpat&volutpat=sapien&convallis=arcu&morbi=sed&odio=augue&odio=aliquam&elementum=erat&eu=volutpat&interdum=in&eu=congue&tincidunt=etiam&in=justo&leo=etiam&maecenas=pretium&pulvinar=iaculis",
    "http://g.co/in/est/risus.html?sit=dictumst&amet=etiam&eleifend=faucibus&pede=cursus&libero=urna&quis=ut&orci=tellus&nullam=nulla&molestie=ut&nibh=erat&in=id&lectus=mauris&pellentesque=vulputate&at=elementum&nulla=nullam&suspendisse=varius&potenti=nulla&cras=facilisi&in=cras&purus=non&eu=velit&magna=nec&vulputate=nisi&luctus=vulputate&cum=nonummy&sociis=maecenas&natoque=tincidunt&penatibus=lacus&et=at&magnis=velit&dis=vivamus&parturient=vel&montes=nulla&nascetur=eget&ridiculus=eros&mus=elementum&vivamus=pellentesque&vestibulum=quisque&sagittis=porta&sapien=volutpat&cum=erat&sociis=quisque&natoque=erat&penatibus=eros&et=viverra&magnis=eget&dis=congue&parturient=eget&montes=semper&nascetur=rutrum&ridiculus=nulla&mus=nunc&etiam=purus&vel=phasellus&augue=in&vestibulum=felis&rutrum=donec&rutrum=semper&neque=sapien&aenean=a&auctor=libero&gravida=nam&sem=dui&praesent=proin&id=leo&massa=odio&id=porttitor&nisl=id&venenatis=consequat&lacinia=in",
    "http://weebly.com/at/nunc/commodo.html?molestie=cubilia&nibh=curae&in=mauris&lectus=viverra&pellentesque=diam&at=vitae&nulla=quam&suspendisse=suspendisse&potenti=potenti&cras=nullam&in=porttitor&purus=lacus&eu=at&magna=turpis&vulputate=donec&luctus=posuere&cum=metus&sociis=vitae&natoque=ipsum&penatibus=aliquam&et=non&magnis=mauris&dis=morbi&parturient=non&montes=lectus&nascetur=aliquam&ridiculus=sit&mus=amet",
    "https://1688.com/felis/ut/at/dolor/quis.jsp?aliquam=vestibulum&lacus=sagittis&morbi=sapien&quis=cum&tortor=sociis&id=natoque&nulla=penatibus&ultrices=et&aliquet=magnis&maecenas=dis&leo=parturient&odio=montes&condimentum=nascetur&id=ridiculus&luctus=mus&nec=etiam&molestie=vel&sed=augue&justo=vestibulum&pellentesque=rutrum&viverra=rutrum&pede=neque&ac=aenean&diam=auctor&cras=gravida&pellentesque=sem&volutpat=praesent",
    "http://woothemes.com/augue/vel/accumsan/tellus/nisi/eu/orci.png?vivamus=velit&vel=vivamus&nulla=vel&eget=nulla&eros=eget&elementum=eros&pellentesque=elementum&quisque=pellentesque&porta=quisque&volutpat=porta&erat=volutpat&quisque=erat&erat=quisque&eros=erat&viverra=eros&eget=viverra&congue=eget&eget=congue&semper=eget&rutrum=semper&nulla=rutrum&nunc=nulla&purus=nunc&phasellus=purus&in=phasellus&felis=in&donec=felis&semper=donec&sapien=semper&a=sapien&libero=a&nam=libero&dui=nam&proin=dui&leo=proin&odio=leo&porttitor=odio&id=porttitor&consequat=id&in=consequat&consequat=in&ut=consequat&nulla=ut&sed=nulla&accumsan=sed&felis=accumsan&ut=felis&at=ut&dolor=at&quis=dolor&odio=quis&consequat=odio&varius=consequat&integer=varius&ac=integer&leo=ac&pellentesque=leo&ultrices=pellentesque&mattis=ultrices&odio=mattis&donec=odio&vitae=donec&nisi=vitae&nam=nisi&ultrices=nam&libero=ultrices&non=libero&mattis=non&pulvinar=mattis&nulla=pulvinar&pede=nulla&ullamcorper=pede&augue=ullamcorper&a=augue&suscipit=a&nulla=suscipit&elit=nulla&ac=elit&nulla=ac&sed=nulla&vel=sed&enim=vel&sit=enim&amet=sit&nunc=amet&viverra=nunc&dapibus=viverra&nulla=dapibus&suscipit=nulla&ligula=suscipit&in=ligula&lacus=in&curabitur=lacus&at=curabitur",
    "http://deviantart.com/augue.js?in=phasellus&ante=sit&vestibulum=amet&ante=erat&ipsum=nulla&primis=tempus&in=vivamus&faucibus=in&orci=felis&luctus=eu&et=sapien&ultrices=cursus&posuere=vestibulum&cubilia=proin&curae=eu&duis=mi&faucibus=nulla&accumsan=ac&odio=enim&curabitur=in",
    "https://flavors.me/tortor/duis/mattis/egestas/metus.jpg?cubilia=morbi&curae=vestibulum&duis=velit&faucibus=id&accumsan=pretium&odio=iaculis&curabitur=diam&convallis=erat&duis=fermentum&consequat=justo&dui=nec&nec=condimentum&nisi=neque&volutpat=sapien&eleifend=placerat&donec=ante&ut=nulla&dolor=justo&morbi=aliquam&vel=quis&lectus=turpis&in=eget&quam=elit&fringilla=sodales&rhoncus=scelerisque&mauris=mauris&enim=sit&leo=amet&rhoncus=eros&sed=suspendisse&vestibulum=accumsan&sit=tortor&amet=quis&cursus=turpis&id=sed&turpis=ante&integer=vivamus&aliquet=tortor&massa=duis&id=mattis&lobortis=egestas&convallis=metus&tortor=aenean&risus=fermentum&dapibus=donec&augue=ut&vel=mauris&accumsan=eget&tellus=massa&nisi=tempor&eu=convallis&orci=nulla&mauris=neque&lacinia=libero&sapien=convallis&quis=eget&libero=eleifend&nullam=luctus&sit=ultricies&amet=eu&turpis=nibh&elementum=quisque&ligula=id&vehicula=justo&consequat=sit&morbi=amet&a=sapien&ipsum=dignissim&integer=vestibulum&a=vestibulum&nibh=ante&in=ipsum&quis=primis&justo=in&maecenas=faucibus&rhoncus=orci&aliquam=luctus&lacus=et&morbi=ultrices&quis=posuere&tortor=cubilia&id=curae&nulla=nulla&ultrices=dapibus&aliquet=dolor&maecenas=vel&leo=est&odio=donec&condimentum=odio&id=justo&luctus=sollicitudin&nec=ut&molestie=suscipit&sed=a&justo=feugiat",
    "https://ucoz.ru/nulla/integer.xml?libero=quis&nullam=orci&sit=eget&amet=orci&turpis=vehicula&elementum=condimentum&ligula=curabitur&vehicula=in&consequat=libero&morbi=ut&a=massa&ipsum=volutpat&integer=convallis&a=morbi&nibh=odio&in=odio&quis=elementum&justo=eu&maecenas=interdum&rhoncus=eu&aliquam=tincidunt&lacus=in&morbi=leo&quis=maecenas&tortor=pulvinar&id=lobortis&nulla=est&ultrices=phasellus&aliquet=sit&maecenas=amet&leo=erat&odio=nulla&condimentum=tempus&id=vivamus&luctus=in&nec=felis&molestie=eu&sed=sapien&justo=cursus&pellentesque=vestibulum&viverra=proin&pede=eu&ac=mi&diam=nulla&cras=ac&pellentesque=enim&volutpat=in&dui=tempor&maecenas=turpis&tristique=nec&est=euismod&et=scelerisque&tempus=quam&semper=turpis&est=adipiscing&quam=lorem&pharetra=vitae&magna=mattis&ac=nibh&consequat=ligula&metus=nec&sapien=sem&ut=duis&nunc=aliquam&vestibulum=convallis&ante=nunc&ipsum=proin&primis=at&in=turpis&faucibus=a&orci=pede&luctus=posuere&et=nonummy&ultrices=integer&posuere=non&cubilia=velit&curae=donec&mauris=diam&viverra=neque&diam=vestibulum&vitae=eget&quam=vulputate&suspendisse=ut&potenti=ultrices&nullam=vel&porttitor=augue&lacus=vestibulum&at=ante&turpis=ipsum&donec=primis&posuere=in&metus=faucibus&vitae=orci&ipsum=luctus&aliquam=et&non=ultrices",
    "https://ocn.ne.jp/vitae/mattis.html?odio=molestie&condimentum=hendrerit&id=at&luctus=vulputate&nec=vitae&molestie=nisl&sed=aenean&justo=lectus&pellentesque=pellentesque&viverra=eget&pede=nunc&ac=donec&diam=quis&cras=orci&pellentesque=eget&volutpat=orci&dui=vehicula&maecenas=condimentum&tristique=curabitur&est=in&et=libero&tempus=ut&semper=massa&est=volutpat&quam=convallis&pharetra=morbi&magna=odio&ac=odio&consequat=elementum&metus=eu&sapien=interdum&ut=eu&nunc=tincidunt&vestibulum=in&ante=leo&ipsum=maecenas&primis=pulvinar&in=lobortis&faucibus=est&orci=phasellus&luctus=sit&et=amet&ultrices=erat&posuere=nulla&cubilia=tempus&curae=vivamus&mauris=in&viverra=felis&diam=eu&vitae=sapien&quam=cursus&suspendisse=vestibulum&potenti=proin&nullam=eu&porttitor=mi&lacus=nulla&at=ac&turpis=enim&donec=in&posuere=tempor&metus=turpis&vitae=nec&ipsum=euismod&aliquam=scelerisque&non=quam&mauris=turpis&morbi=adipiscing&non=lorem&lectus=vitae&aliquam=mattis&sit=nibh&amet=ligula&diam=nec&in=sem&magna=duis&bibendum=aliquam&imperdiet=convallis&nullam=nunc&orci=proin&pede=at&venenatis=turpis&non=a&sodales=pede&sed=posuere&tincidunt=nonummy",
    "https://alexa.com/dapibus/duis/at/velit/eu.json?eget=pede&orci=justo&vehicula=eu&condimentum=massa&curabitur=donec&in=dapibus&libero=duis&ut=at&massa=velit&volutpat=eu&convallis=est&morbi=congue&odio=elementum&odio=in&elementum=hac&eu=habitasse&interdum=platea&eu=dictumst&tincidunt=morbi&in=vestibulum&leo=velit&maecenas=id&pulvinar=pretium&lobortis=iaculis&est=diam&phasellus=erat&sit=fermentum&amet=justo&erat=nec&nulla=condimentum&tempus=neque&vivamus=sapien&in=placerat&felis=ante&eu=nulla&sapien=justo",
    "https://microsoft.com/mi.aspx?et=mattis&ultrices=egestas&posuere=metus&cubilia=aenean&curae=fermentum&donec=donec&pharetra=ut&magna=mauris&vestibulum=eget",
    "https://yolasite.com/lobortis.jpg?justo=amet&etiam=sem&pretium=fusce&iaculis=consequat&justo=nulla&in=nisl&hac=nunc&habitasse=nisl&platea=duis&dictumst=bibendum&etiam=felis&faucibus=sed&cursus=interdum&urna=venenatis&ut=turpis&tellus=enim&nulla=blandit&ut=mi&erat=in&id=porttitor&mauris=pede&vulputate=justo&elementum=eu&nullam=massa&varius=donec&nulla=dapibus&facilisi=duis&cras=at&non=velit&velit=eu&nec=est",
    "https://engadget.com/velit/eu.xml?sagittis=lectus&sapien=suspendisse&cum=potenti&sociis=in&natoque=eleifend&penatibus=quam&et=a&magnis=odio&dis=in&parturient=hac&montes=habitasse&nascetur=platea&ridiculus=dictumst&mus=maecenas&etiam=ut&vel=massa&augue=quis",
    "http://kickstarter.com/tincidunt/eu/felis/fusce/posuere/felis/sed.jsp?in=adipiscing&hac=elit&habitasse=proin&platea=risus&dictumst=praesent&maecenas=lectus&ut=vestibulum&massa=quam&quis=sapien&augue=varius&luctus=ut&tincidunt=blandit&nulla=non&mollis=interdum&molestie=in&lorem=ante&quisque=vestibulum&ut=ante&erat=ipsum&curabitur=primis&gravida=in&nisi=faucibus&at=orci&nibh=luctus&in=et&hac=ultrices&habitasse=posuere&platea=cubilia&dictumst=curae&aliquam=duis&augue=faucibus&quam=accumsan&sollicitudin=odio&vitae=curabitur&consectetuer=convallis&eget=duis&rutrum=consequat&at=dui&lorem=nec&integer=nisi&tincidunt=volutpat&ante=eleifend&vel=donec&ipsum=ut&praesent=dolor&blandit=morbi&lacinia=vel&erat=lectus&vestibulum=in&sed=quam&magna=fringilla&at=rhoncus&nunc=mauris&commodo=enim&placerat=leo&praesent=rhoncus&blandit=sed&nam=vestibulum&nulla=sit&integer=amet&pede=cursus&justo=id&lacinia=turpis&eget=integer&tincidunt=aliquet&eget=massa&tempus=id&vel=lobortis&pede=convallis&morbi=tortor&porttitor=risus&lorem=dapibus&id=augue&ligula=vel&suspendisse=accumsan&ornare=tellus&consequat=nisi&lectus=eu&in=orci&est=mauris&risus=lacinia&auctor=sapien&sed=quis&tristique=libero&in=nullam&tempus=sit&sit=amet&amet=turpis&sem=elementum&fusce=ligula&consequat=vehicula&nulla=consequat&nisl=morbi&nunc=a&nisl=ipsum&duis=integer&bibendum=a",
    "https://goodreads.com/consequat/lectus/in/est.xml?donec=justo&vitae=eu&nisi=massa&nam=donec&ultrices=dapibus&libero=duis&non=at&mattis=velit&pulvinar=eu&nulla=est&pede=congue&ullamcorper=elementum&augue=in&a=hac&suscipit=habitasse&nulla=platea&elit=dictumst&ac=morbi&nulla=vestibulum&sed=velit&vel=id&enim=pretium&sit=iaculis&amet=diam&nunc=erat&viverra=fermentum&dapibus=justo&nulla=nec&suscipit=condimentum&ligula=neque&in=sapien&lacus=placerat&curabitur=ante&at=nulla&ipsum=justo&ac=aliquam&tellus=quis",
    "https://ucsd.edu/maecenas/tincidunt.html?ut=vel&erat=enim&curabitur=sit&gravida=amet&nisi=nunc&at=viverra&nibh=dapibus&in=nulla&hac=suscipit&habitasse=ligula&platea=in&dictumst=lacus&aliquam=curabitur&augue=at&quam=ipsum&sollicitudin=ac&vitae=tellus&consectetuer=semper&eget=interdum&rutrum=mauris&at=ullamcorper&lorem=purus&integer=sit&tincidunt=amet",
    "http://photobucket.com/dui/maecenas/tristique/est.png?a=donec&ipsum=ut&integer=dolor&a=morbi&nibh=vel&in=lectus&quis=in&justo=quam&maecenas=fringilla&rhoncus=rhoncus&aliquam=mauris&lacus=enim&morbi=leo&quis=rhoncus&tortor=sed&id=vestibulum&nulla=sit&ultrices=amet&aliquet=cursus&maecenas=id&leo=turpis&odio=integer&condimentum=aliquet&id=massa&luctus=id&nec=lobortis&molestie=convallis&sed=tortor&justo=risus&pellentesque=dapibus&viverra=augue&pede=vel&ac=accumsan&diam=tellus&cras=nisi&pellentesque=eu&volutpat=orci&dui=mauris&maecenas=lacinia&tristique=sapien&est=quis&et=libero&tempus=nullam&semper=sit&est=amet&quam=turpis&pharetra=elementum&magna=ligula&ac=vehicula&consequat=consequat",
    "http://devhub.com/eget/eleifend/luctus/ultricies/eu/nibh/quisque.json?justo=nulla&etiam=suscipit&pretium=ligula&iaculis=in&justo=lacus&in=curabitur&hac=at&habitasse=ipsum&platea=ac&dictumst=tellus&etiam=semper&faucibus=interdum",
    "https://yolasite.com/cubilia/curae/nulla/dapibus/dolor/vel.jsp?in=posuere&tempor=cubilia&turpis=curae&nec=donec&euismod=pharetra&scelerisque=magna&quam=vestibulum&turpis=aliquet&adipiscing=ultrices&lorem=erat&vitae=tortor&mattis=sollicitudin&nibh=mi&ligula=sit&nec=amet&sem=lobortis&duis=sapien&aliquam=sapien&convallis=non&nunc=mi&proin=integer&at=ac&turpis=neque&a=duis&pede=bibendum&posuere=morbi&nonummy=non&integer=quam&non=nec&velit=dui&donec=luctus&diam=rutrum&neque=nulla&vestibulum=tellus&eget=in&vulputate=sagittis&ut=dui&ultrices=vel&vel=nisl&augue=duis&vestibulum=ac&ante=nibh&ipsum=fusce&primis=lacus&in=purus&faucibus=aliquet&orci=at&luctus=feugiat&et=non&ultrices=pretium&posuere=quis&cubilia=lectus&curae=suspendisse&donec=potenti&pharetra=in&magna=eleifend&vestibulum=quam&aliquet=a&ultrices=odio&erat=in&tortor=hac&sollicitudin=habitasse&mi=platea&sit=dictumst&amet=maecenas&lobortis=ut&sapien=massa&sapien=quis&non=augue&mi=luctus&integer=tincidunt&ac=nulla&neque=mollis&duis=molestie&bibendum=lorem&morbi=quisque&non=ut&quam=erat&nec=curabitur&dui=gravida&luctus=nisi&rutrum=at&nulla=nibh&tellus=in&in=hac&sagittis=habitasse&dui=platea&vel=dictumst&nisl=aliquam&duis=augue&ac=quam&nibh=sollicitudin&fusce=vitae",
    "https://google.cn/sit/amet/nulla.png?pretium=vel&quis=augue&lectus=vestibulum&suspendisse=ante&potenti=ipsum&in=primis&eleifend=in&quam=faucibus&a=orci&odio=luctus&in=et&hac=ultrices&habitasse=posuere&platea=cubilia&dictumst=curae&maecenas=donec&ut=pharetra&massa=magna&quis=vestibulum&augue=aliquet&luctus=ultrices&tincidunt=erat&nulla=tortor&mollis=sollicitudin&molestie=mi&lorem=sit&quisque=amet&ut=lobortis&erat=sapien&curabitur=sapien&gravida=non&nisi=mi&at=integer&nibh=ac&in=neque&hac=duis&habitasse=bibendum&platea=morbi&dictumst=non&aliquam=quam&augue=nec&quam=dui&sollicitudin=luctus&vitae=rutrum&consectetuer=nulla&eget=tellus&rutrum=in&at=sagittis&lorem=dui&integer=vel&tincidunt=nisl&ante=duis&vel=ac&ipsum=nibh&praesent=fusce&blandit=lacus&lacinia=purus&erat=aliquet&vestibulum=at&sed=feugiat&magna=non&at=pretium&nunc=quis&commodo=lectus&placerat=suspendisse&praesent=potenti&blandit=in&nam=eleifend&nulla=quam&integer=a&pede=odio&justo=in&lacinia=hac&eget=habitasse&tincidunt=platea&eget=dictumst",
    "http://archive.org/interdum/venenatis/turpis/enim/blandit.xml?etiam=bibendum&vel=felis&augue=sed&vestibulum=interdum&rutrum=venenatis&rutrum=turpis&neque=enim&aenean=blandit&auctor=mi&gravida=in&sem=porttitor&praesent=pede&id=justo&massa=eu&id=massa&nisl=donec&venenatis=dapibus&lacinia=duis&aenean=at&sit=velit&amet=eu&justo=est&morbi=congue&ut=elementum&odio=in&cras=hac&mi=habitasse",
    "http://slate.com/hendrerit/at/vulputate/vitae/nisl/aenean.html?velit=proin&donec=eu&diam=mi&neque=nulla&vestibulum=ac&eget=enim&vulputate=in&ut=tempor&ultrices=turpis&vel=nec&augue=euismod&vestibulum=scelerisque&ante=quam&ipsum=turpis&primis=adipiscing&in=lorem&faucibus=vitae&orci=mattis&luctus=nibh&et=ligula&ultrices=nec&posuere=sem&cubilia=duis&curae=aliquam&donec=convallis&pharetra=nunc&magna=proin&vestibulum=at&aliquet=turpis&ultrices=a&erat=pede&tortor=posuere&sollicitudin=nonummy&mi=integer&sit=non&amet=velit&lobortis=donec&sapien=diam&sapien=neque&non=vestibulum&mi=eget&integer=vulputate&ac=ut&neque=ultrices&duis=vel&bibendum=augue&morbi=vestibulum&non=ante&quam=ipsum&nec=primis&dui=in&luctus=faucibus&rutrum=orci&nulla=luctus&tellus=et&in=ultrices&sagittis=posuere&dui=cubilia&vel=curae&nisl=donec&duis=pharetra&ac=magna&nibh=vestibulum&fusce=aliquet&lacus=ultrices&purus=erat&aliquet=tortor&at=sollicitudin&feugiat=mi",
    "https://wikia.com/luctus/et/ultrices/posuere.jsp?sagittis=ac&nam=nulla&congue=sed&risus=vel&semper=enim&porta=sit&volutpat=amet&quam=nunc&pede=viverra&lobortis=dapibus&ligula=nulla&sit=suscipit&amet=ligula&eleifend=in&pede=lacus&libero=curabitur&quis=at&orci=ipsum&nullam=ac&molestie=tellus&nibh=semper&in=interdum&lectus=mauris&pellentesque=ullamcorper&at=purus&nulla=sit&suspendisse=amet&potenti=nulla&cras=quisque&in=arcu&purus=libero&eu=rutrum&magna=ac&vulputate=lobortis&luctus=vel&cum=dapibus&sociis=at&natoque=diam&penatibus=nam&et=tristique&magnis=tortor",
    "http://google.com.hk/phasellus/sit/amet/erat.jpg?nunc=eleifend&donec=donec&quis=ut&orci=dolor&eget=morbi&orci=vel&vehicula=lectus&condimentum=in&curabitur=quam&in=fringilla&libero=rhoncus&ut=mauris&massa=enim&volutpat=leo&convallis=rhoncus&morbi=sed&odio=vestibulum&odio=sit&elementum=amet&eu=cursus&interdum=id&eu=turpis&tincidunt=integer&in=aliquet&leo=massa&maecenas=id&pulvinar=lobortis&lobortis=convallis&est=tortor&phasellus=risus&sit=dapibus&amet=augue&erat=vel&nulla=accumsan&tempus=tellus&vivamus=nisi&in=eu&felis=orci&eu=mauris&sapien=lacinia&cursus=sapien&vestibulum=quis&proin=libero&eu=nullam&mi=sit&nulla=amet&ac=turpis&enim=elementum&in=ligula&tempor=vehicula&turpis=consequat&nec=morbi&euismod=a&scelerisque=ipsum&quam=integer&turpis=a&adipiscing=nibh&lorem=in&vitae=quis&mattis=justo&nibh=maecenas&ligula=rhoncus&nec=aliquam&sem=lacus&duis=morbi&aliquam=quis&convallis=tortor&nunc=id&proin=nulla&at=ultrices&turpis=aliquet&a=maecenas&pede=leo&posuere=odio&nonummy=condimentum&integer=id&non=luctus&velit=nec&donec=molestie&diam=sed&neque=justo&vestibulum=pellentesque&eget=viverra&vulputate=pede&ut=ac&ultrices=diam&vel=cras&augue=pellentesque",
    "https://live.com/ac/est/lacinia.aspx?quis=mi&turpis=in&sed=porttitor&ante=pede&vivamus=justo&tortor=eu&duis=massa&mattis=donec&egestas=dapibus&metus=duis&aenean=at&fermentum=velit&donec=eu&ut=est&mauris=congue&eget=elementum&massa=in&tempor=hac&convallis=habitasse&nulla=platea&neque=dictumst&libero=morbi&convallis=vestibulum&eget=velit&eleifend=id&luctus=pretium&ultricies=iaculis&eu=diam&nibh=erat&quisque=fermentum&id=justo&justo=nec&sit=condimentum&amet=neque&sapien=sapien&dignissim=placerat&vestibulum=ante&vestibulum=nulla&ante=justo&ipsum=aliquam&primis=quis&in=turpis&faucibus=eget&orci=elit&luctus=sodales&et=scelerisque&ultrices=mauris&posuere=sit&cubilia=amet&curae=eros&nulla=suspendisse&dapibus=accumsan&dolor=tortor&vel=quis&est=turpis&donec=sed&odio=ante&justo=vivamus&sollicitudin=tortor&ut=duis&suscipit=mattis&a=egestas&feugiat=metus&et=aenean&eros=fermentum&vestibulum=donec&ac=ut&est=mauris&lacinia=eget&nisi=massa&venenatis=tempor&tristique=convallis&fusce=nulla&congue=neque&diam=libero&id=convallis&ornare=eget&imperdiet=eleifend&sapien=luctus&urna=ultricies&pretium=eu",
    "https://house.gov/condimentum.json?magna=tempor&ac=convallis",
    "https://dell.com/consequat/varius/integer.png?eu=velit&orci=nec&mauris=nisi&lacinia=vulputate&sapien=nonummy&quis=maecenas&libero=tincidunt&nullam=lacus&sit=at&amet=velit&turpis=vivamus&elementum=vel&ligula=nulla&vehicula=eget&consequat=eros&morbi=elementum&a=pellentesque&ipsum=quisque",
    "http://senate.gov/ac/tellus/semper/interdum.aspx?luctus=tortor&et=quis&ultrices=turpis&posuere=sed&cubilia=ante&curae=vivamus&donec=tortor&pharetra=duis&magna=mattis&vestibulum=egestas&aliquet=metus&ultrices=aenean&erat=fermentum&tortor=donec&sollicitudin=ut&mi=mauris&sit=eget&amet=massa&lobortis=tempor&sapien=convallis&sapien=nulla&non=neque&mi=libero&integer=convallis&ac=eget&neque=eleifend&duis=luctus&bibendum=ultricies&morbi=eu&non=nibh&quam=quisque&nec=id&dui=justo&luctus=sit&rutrum=amet&nulla=sapien&tellus=dignissim&in=vestibulum&sagittis=vestibulum&dui=ante&vel=ipsum&nisl=primis&duis=in&ac=faucibus&nibh=orci&fusce=luctus&lacus=et&purus=ultrices&aliquet=posuere&at=cubilia&feugiat=curae&non=nulla&pretium=dapibus&quis=dolor&lectus=vel&suspendisse=est&potenti=donec&in=odio&eleifend=justo&quam=sollicitudin&a=ut&odio=suscipit&in=a&hac=feugiat&habitasse=et&platea=eros&dictumst=vestibulum&maecenas=ac&ut=est&massa=lacinia&quis=nisi&augue=venenatis&luctus=tristique&tincidunt=fusce&nulla=congue&mollis=diam&molestie=id&lorem=ornare&quisque=imperdiet&ut=sapien&erat=urna&curabitur=pretium&gravida=nisl&nisi=ut&at=volutpat&nibh=sapien&in=arcu",
    "https://upenn.edu/interdum/mauris/non/ligula/pellentesque/ultrices.xml?in=donec&congue=ut&etiam=mauris&justo=eget&etiam=massa&pretium=tempor&iaculis=convallis&justo=nulla&in=neque&hac=libero&habitasse=convallis&platea=eget&dictumst=eleifend&etiam=luctus&faucibus=ultricies&cursus=eu&urna=nibh&ut=quisque&tellus=id&nulla=justo&ut=sit&erat=amet&id=sapien&mauris=dignissim&vulputate=vestibulum&elementum=vestibulum&nullam=ante&varius=ipsum&nulla=primis&facilisi=in&cras=faucibus&non=orci&velit=luctus&nec=et&nisi=ultrices&vulputate=posuere&nonummy=cubilia&maecenas=curae&tincidunt=nulla&lacus=dapibus&at=dolor&velit=vel&vivamus=est&vel=donec&nulla=odio&eget=justo&eros=sollicitudin&elementum=ut&pellentesque=suscipit&quisque=a&porta=feugiat&volutpat=et&erat=eros&quisque=vestibulum&erat=ac&eros=est&viverra=lacinia&eget=nisi&congue=venenatis&eget=tristique&semper=fusce&rutrum=congue&nulla=diam&nunc=id&purus=ornare&phasellus=imperdiet&in=sapien&felis=urna&donec=pretium&semper=nisl&sapien=ut&a=volutpat&libero=sapien&nam=arcu&dui=sed&proin=augue&leo=aliquam&odio=erat&porttitor=volutpat&id=in&consequat=congue&in=etiam&consequat=justo&ut=etiam&nulla=pretium&sed=iaculis&accumsan=justo&felis=in&ut=hac&at=habitasse&dolor=platea&quis=dictumst",
    "http://wix.com/phasellus/in/felis.jpg?id=nec&sapien=condimentum&in=neque&sapien=sapien&iaculis=placerat&congue=ante&vivamus=nulla&metus=justo&arcu=aliquam&adipiscing=quis&molestie=turpis&hendrerit=eget&at=elit&vulputate=sodales&vitae=scelerisque&nisl=mauris&aenean=sit&lectus=amet&pellentesque=eros&eget=suspendisse&nunc=accumsan&donec=tortor&quis=quis&orci=turpis&eget=sed&orci=ante&vehicula=vivamus",
    "http://comsenz.com/ut.jpg?etiam=quis&vel=libero&augue=nullam&vestibulum=sit&rutrum=amet&rutrum=turpis&neque=elementum&aenean=ligula&auctor=vehicula&gravida=consequat&sem=morbi&praesent=a&id=ipsum&massa=integer&id=a&nisl=nibh&venenatis=in&lacinia=quis&aenean=justo&sit=maecenas&amet=rhoncus&justo=aliquam&morbi=lacus&ut=morbi&odio=quis&cras=tortor&mi=id&pede=nulla&malesuada=ultrices&in=aliquet&imperdiet=maecenas&et=leo&commodo=odio&vulputate=condimentum&justo=id&in=luctus&blandit=nec&ultrices=molestie&enim=sed&lorem=justo&ipsum=pellentesque&dolor=viverra&sit=pede&amet=ac&consectetuer=diam&adipiscing=cras&elit=pellentesque&proin=volutpat&interdum=dui&mauris=maecenas&non=tristique&ligula=est&pellentesque=et&ultrices=tempus&phasellus=semper&id=est&sapien=quam&in=pharetra&sapien=magna&iaculis=ac&congue=consequat&vivamus=metus&metus=sapien&arcu=ut&adipiscing=nunc&molestie=vestibulum&hendrerit=ante",
    "http://nymag.com/in.jpg?tellus=iaculis&in=justo&sagittis=in&dui=hac&vel=habitasse&nisl=platea&duis=dictumst&ac=etiam&nibh=faucibus&fusce=cursus&lacus=urna&purus=ut&aliquet=tellus&at=nulla&feugiat=ut&non=erat&pretium=id&quis=mauris&lectus=vulputate&suspendisse=elementum&potenti=nullam&in=varius&eleifend=nulla&quam=facilisi&a=cras&odio=non&in=velit&hac=nec&habitasse=nisi&platea=vulputate&dictumst=nonummy&maecenas=maecenas&ut=tincidunt&massa=lacus&quis=at&augue=velit&luctus=vivamus&tincidunt=vel&nulla=nulla&mollis=eget&molestie=eros&lorem=elementum&quisque=pellentesque&ut=quisque&erat=porta&curabitur=volutpat&gravida=erat&nisi=quisque&at=erat&nibh=eros&in=viverra&hac=eget&habitasse=congue&platea=eget&dictumst=semper&aliquam=rutrum&augue=nulla&quam=nunc&sollicitudin=purus&vitae=phasellus&consectetuer=in&eget=felis&rutrum=donec&at=semper&lorem=sapien&integer=a&tincidunt=libero&ante=nam&vel=dui&ipsum=proin&praesent=leo&blandit=odio&lacinia=porttitor&erat=id&vestibulum=consequat&sed=in&magna=consequat&at=ut&nunc=nulla&commodo=sed&placerat=accumsan&praesent=felis&blandit=ut&nam=at&nulla=dolor&integer=quis&pede=odio&justo=consequat&lacinia=varius&eget=integer&tincidunt=ac&eget=leo&tempus=pellentesque&vel=ultrices&pede=mattis&morbi=odio&porttitor=donec&lorem=vitae&id=nisi",
    "https://tripadvisor.com/arcu/sed/augue/aliquam.json?nec=magna&nisi=ac&volutpat=consequat&eleifend=metus&donec=sapien&ut=ut&dolor=nunc&morbi=vestibulum&vel=ante&lectus=ipsum&in=primis&quam=in&fringilla=faucibus&rhoncus=orci&mauris=luctus&enim=et&leo=ultrices&rhoncus=posuere&sed=cubilia&vestibulum=curae&sit=mauris&amet=viverra&cursus=diam&id=vitae&turpis=quam&integer=suspendisse&aliquet=potenti&massa=nullam&id=porttitor&lobortis=lacus&convallis=at&tortor=turpis&risus=donec&dapibus=posuere&augue=metus&vel=vitae&accumsan=ipsum&tellus=aliquam&nisi=non&eu=mauris&orci=morbi&mauris=non&lacinia=lectus&sapien=aliquam&quis=sit&libero=amet&nullam=diam&sit=in&amet=magna&turpis=bibendum&elementum=imperdiet&ligula=nullam&vehicula=orci&consequat=pede&morbi=venenatis&a=non&ipsum=sodales&integer=sed&a=tincidunt&nibh=eu&in=felis&quis=fusce&justo=posuere&maecenas=felis&rhoncus=sed&aliquam=lacus&lacus=morbi&morbi=sem&quis=mauris&tortor=laoreet&id=ut&nulla=rhoncus&ultrices=aliquet&aliquet=pulvinar&maecenas=sed&leo=nisl&odio=nunc&condimentum=rhoncus&id=dui&luctus=vel&nec=sem&molestie=sed&sed=sagittis&justo=nam&pellentesque=congue&viverra=risus&pede=semper",
    "https://mapy.cz/molestie/nibh/in.json?nunc=vivamus&vestibulum=in&ante=felis&ipsum=eu&primis=sapien&in=cursus&faucibus=vestibulum&orci=proin&luctus=eu&et=mi&ultrices=nulla&posuere=ac&cubilia=enim&curae=in&mauris=tempor&viverra=turpis&diam=nec&vitae=euismod&quam=scelerisque&suspendisse=quam&potenti=turpis&nullam=adipiscing&porttitor=lorem&lacus=vitae&at=mattis&turpis=nibh&donec=ligula&posuere=nec&metus=sem&vitae=duis&ipsum=aliquam&aliquam=convallis&non=nunc&mauris=proin&morbi=at&non=turpis&lectus=a&aliquam=pede&sit=posuere&amet=nonummy&diam=integer&in=non&magna=velit&bibendum=donec&imperdiet=diam&nullam=neque&orci=vestibulum&pede=eget&venenatis=vulputate&non=ut&sodales=ultrices&sed=vel&tincidunt=augue&eu=vestibulum&felis=ante&fusce=ipsum&posuere=primis&felis=in&sed=faucibus&lacus=orci&morbi=luctus&sem=et&mauris=ultrices&laoreet=posuere&ut=cubilia&rhoncus=curae&aliquet=donec&pulvinar=pharetra&sed=magna&nisl=vestibulum&nunc=aliquet&rhoncus=ultrices&dui=erat&vel=tortor&sem=sollicitudin&sed=mi&sagittis=sit&nam=amet&congue=lobortis&risus=sapien&semper=sapien&porta=non&volutpat=mi&quam=integer",
    "https://1und1.de/orci/luctus/et/ultrices.png?magnis=laoreet&dis=ut&parturient=rhoncus&montes=aliquet&nascetur=pulvinar&ridiculus=sed&mus=nisl&etiam=nunc&vel=rhoncus&augue=dui&vestibulum=vel&rutrum=sem&rutrum=sed&neque=sagittis&aenean=nam&auctor=congue&gravida=risus&sem=semper&praesent=porta&id=volutpat&massa=quam&id=pede&nisl=lobortis&venenatis=ligula&lacinia=sit&aenean=amet&sit=eleifend&amet=pede&justo=libero&morbi=quis&ut=orci&odio=nullam&cras=molestie&mi=nibh&pede=in&malesuada=lectus&in=pellentesque&imperdiet=at&et=nulla&commodo=suspendisse&vulputate=potenti&justo=cras&in=in&blandit=purus&ultrices=eu&enim=magna&lorem=vulputate&ipsum=luctus&dolor=cum&sit=sociis&amet=natoque&consectetuer=penatibus&adipiscing=et&elit=magnis&proin=dis&interdum=parturient&mauris=montes&non=nascetur&ligula=ridiculus&pellentesque=mus&ultrices=vivamus&phasellus=vestibulum&id=sagittis&sapien=sapien&in=cum&sapien=sociis&iaculis=natoque&congue=penatibus&vivamus=et&metus=magnis&arcu=dis&adipiscing=parturient&molestie=montes&hendrerit=nascetur&at=ridiculus&vulputate=mus&vitae=etiam&nisl=vel&aenean=augue&lectus=vestibulum&pellentesque=rutrum&eget=rutrum&nunc=neque",
    "https://soup.io/duis/consequat/dui.json?aenean=quis&auctor=turpis&gravida=eget&sem=elit&praesent=sodales&id=scelerisque&massa=mauris&id=sit&nisl=amet&venenatis=eros&lacinia=suspendisse&aenean=accumsan&sit=tortor&amet=quis&justo=turpis&morbi=sed&ut=ante&odio=vivamus&cras=tortor&mi=duis&pede=mattis&malesuada=egestas&in=metus&imperdiet=aenean&et=fermentum&commodo=donec&vulputate=ut&justo=mauris&in=eget&blandit=massa&ultrices=tempor&enim=convallis&lorem=nulla&ipsum=neque&dolor=libero&sit=convallis&amet=eget&consectetuer=eleifend&adipiscing=luctus&elit=ultricies&proin=eu&interdum=nibh&mauris=quisque&non=id&ligula=justo&pellentesque=sit&ultrices=amet&phasellus=sapien&id=dignissim&sapien=vestibulum&in=vestibulum&sapien=ante&iaculis=ipsum&congue=primis&vivamus=in&metus=faucibus&arcu=orci&adipiscing=luctus&molestie=et&hendrerit=ultrices&at=posuere&vulputate=cubilia&vitae=curae&nisl=nulla&aenean=dapibus&lectus=dolor&pellentesque=vel",
    "http://aol.com/odio/elementum.jsp?quam=imperdiet&nec=sapien&dui=urna&luctus=pretium&rutrum=nisl&nulla=ut&tellus=volutpat&in=sapien&sagittis=arcu",
    "http://sina.com.cn/porttitor/pede/justo.html?venenatis=imperdiet&tristique=nullam&fusce=orci&congue=pede&diam=venenatis&id=non&ornare=sodales&imperdiet=sed&sapien=tincidunt&urna=eu&pretium=felis&nisl=fusce&ut=posuere&volutpat=felis&sapien=sed&arcu=lacus&sed=morbi&augue=sem&aliquam=mauris&erat=laoreet&volutpat=ut&in=rhoncus&congue=aliquet&etiam=pulvinar&justo=sed&etiam=nisl&pretium=nunc&iaculis=rhoncus&justo=dui",
    "https://edublogs.org/amet/cursus/id/turpis/integer/aliquet.jsp?mi=massa&nulla=donec&ac=dapibus&enim=duis&in=at&tempor=velit&turpis=eu&nec=est&euismod=congue&scelerisque=elementum&quam=in&turpis=hac&adipiscing=habitasse&lorem=platea&vitae=dictumst&mattis=morbi&nibh=vestibulum&ligula=velit&nec=id&sem=pretium&duis=iaculis&aliquam=diam&convallis=erat&nunc=fermentum&proin=justo&at=nec&turpis=condimentum&a=neque&pede=sapien&posuere=placerat&nonummy=ante&integer=nulla&non=justo&velit=aliquam&donec=quis&diam=turpis&neque=eget&vestibulum=elit&eget=sodales&vulputate=scelerisque&ut=mauris&ultrices=sit&vel=amet&augue=eros&vestibulum=suspendisse&ante=accumsan&ipsum=tortor&primis=quis&in=turpis&faucibus=sed&orci=ante&luctus=vivamus&et=tortor&ultrices=duis&posuere=mattis&cubilia=egestas",
    "http://pcworld.com/nisl/nunc/nisl/duis/bibendum/felis.aspx?sagittis=in&dui=ante&vel=vestibulum&nisl=ante&duis=ipsum&ac=primis&nibh=in&fusce=faucibus&lacus=orci&purus=luctus&aliquet=et&at=ultrices&feugiat=posuere&non=cubilia&pretium=curae&quis=duis&lectus=faucibus&suspendisse=accumsan&potenti=odio&in=curabitur&eleifend=convallis&quam=duis&a=consequat&odio=dui&in=nec&hac=nisi&habitasse=volutpat&platea=eleifend&dictumst=donec&maecenas=ut&ut=dolor&massa=morbi&quis=vel&augue=lectus&luctus=in&tincidunt=quam&nulla=fringilla&mollis=rhoncus&molestie=mauris&lorem=enim&quisque=leo&ut=rhoncus&erat=sed&curabitur=vestibulum&gravida=sit&nisi=amet&at=cursus&nibh=id&in=turpis&hac=integer&habitasse=aliquet&platea=massa&dictumst=id&aliquam=lobortis&augue=convallis&quam=tortor&sollicitudin=risus&vitae=dapibus&consectetuer=augue&eget=vel&rutrum=accumsan&at=tellus&lorem=nisi&integer=eu&tincidunt=orci&ante=mauris&vel=lacinia&ipsum=sapien&praesent=quis&blandit=libero&lacinia=nullam&erat=sit&vestibulum=amet&sed=turpis&magna=elementum&at=ligula",
    "http://npr.org/sapien.xml?non=metus&mi=arcu&integer=adipiscing&ac=molestie&neque=hendrerit&duis=at&bibendum=vulputate&morbi=vitae&non=nisl&quam=aenean&nec=lectus&dui=pellentesque&luctus=eget&rutrum=nunc&nulla=donec&tellus=quis&in=orci&sagittis=eget&dui=orci&vel=vehicula&nisl=condimentum&duis=curabitur&ac=in&nibh=libero&fusce=ut&lacus=massa&purus=volutpat&aliquet=convallis&at=morbi&feugiat=odio&non=odio&pretium=elementum&quis=eu&lectus=interdum&suspendisse=eu&potenti=tincidunt&in=in&eleifend=leo&quam=maecenas&a=pulvinar&odio=lobortis&in=est&hac=phasellus&habitasse=sit&platea=amet&dictumst=erat&maecenas=nulla&ut=tempus&massa=vivamus&quis=in&augue=felis&luctus=eu&tincidunt=sapien&nulla=cursus&mollis=vestibulum&molestie=proin&lorem=eu&quisque=mi&ut=nulla&erat=ac&curabitur=enim",
    "https://icq.com/eu/sapien/cursus/vestibulum/proin.jpg?sapien=a&non=suscipit&mi=nulla&integer=elit&ac=ac&neque=nulla&duis=sed&bibendum=vel&morbi=enim&non=sit&quam=amet&nec=nunc&dui=viverra&luctus=dapibus&rutrum=nulla&nulla=suscipit&tellus=ligula&in=in&sagittis=lacus&dui=curabitur&vel=at&nisl=ipsum&duis=ac&ac=tellus&nibh=semper&fusce=interdum&lacus=mauris&purus=ullamcorper&aliquet=purus&at=sit&feugiat=amet",
    "http://shinystat.com/est/lacinia.aspx?velit=primis&donec=in&diam=faucibus&neque=orci&vestibulum=luctus&eget=et&vulputate=ultrices&ut=posuere&ultrices=cubilia&vel=curae&augue=donec&vestibulum=pharetra&ante=magna&ipsum=vestibulum&primis=aliquet&in=ultrices&faucibus=erat&orci=tortor&luctus=sollicitudin&et=mi&ultrices=sit&posuere=amet&cubilia=lobortis&curae=sapien&donec=sapien&pharetra=non&magna=mi&vestibulum=integer&aliquet=ac&ultrices=neque&erat=duis&tortor=bibendum&sollicitudin=morbi&mi=non&sit=quam&amet=nec&lobortis=dui&sapien=luctus&sapien=rutrum&non=nulla&mi=tellus&integer=in&ac=sagittis&neque=dui&duis=vel&bibendum=nisl&morbi=duis&non=ac",
    "http://e-recht24.de/in/faucibus/orci/luctus/et/ultrices/posuere.png?ut=orci&dolor=luctus&morbi=et&vel=ultrices&lectus=posuere&in=cubilia&quam=curae&fringilla=mauris&rhoncus=viverra&mauris=diam&enim=vitae&leo=quam&rhoncus=suspendisse&sed=potenti&vestibulum=nullam&sit=porttitor&amet=lacus&cursus=at&id=turpis&turpis=donec",
    "https://yahoo.com/penatibus/et/magnis/dis/parturient/montes.jpg?a=habitasse&suscipit=platea&nulla=dictumst&elit=maecenas&ac=ut&nulla=massa&sed=quis&vel=augue&enim=luctus&sit=tincidunt&amet=nulla&nunc=mollis&viverra=molestie&dapibus=lorem",
    "http://xing.com/tellus/in/sagittis/dui/vel/nisl/duis.jpg?libero=tempus&quis=semper&orci=est&nullam=quam&molestie=pharetra&nibh=magna&in=ac&lectus=consequat&pellentesque=metus&at=sapien&nulla=ut&suspendisse=nunc&potenti=vestibulum&cras=ante&in=ipsum&purus=primis&eu=in&magna=faucibus&vulputate=orci&luctus=luctus&cum=et&sociis=ultrices&natoque=posuere&penatibus=cubilia&et=curae&magnis=mauris&dis=viverra&parturient=diam",
    "http://whitehouse.gov/velit/eu/est/congue/elementum.js?vel=quam&lectus=turpis&in=adipiscing&quam=lorem&fringilla=vitae&rhoncus=mattis&mauris=nibh&enim=ligula&leo=nec&rhoncus=sem&sed=duis&vestibulum=aliquam&sit=convallis&amet=nunc&cursus=proin&id=at&turpis=turpis&integer=a&aliquet=pede&massa=posuere&id=nonummy&lobortis=integer&convallis=non&tortor=velit&risus=donec&dapibus=diam&augue=neque&vel=vestibulum&accumsan=eget&tellus=vulputate&nisi=ut&eu=ultrices&orci=vel&mauris=augue&lacinia=vestibulum&sapien=ante&quis=ipsum&libero=primis&nullam=in&sit=faucibus&amet=orci&turpis=luctus&elementum=et&ligula=ultrices&vehicula=posuere&consequat=cubilia&morbi=curae&a=donec&ipsum=pharetra&integer=magna&a=vestibulum&nibh=aliquet&in=ultrices&quis=erat&justo=tortor&maecenas=sollicitudin&rhoncus=mi&aliquam=sit&lacus=amet&morbi=lobortis&quis=sapien&tortor=sapien&id=non&nulla=mi&ultrices=integer&aliquet=ac",
    "http://4shared.com/quis.html?dui=suscipit&proin=nulla&leo=elit&odio=ac&porttitor=nulla&id=sed&consequat=vel&in=enim&consequat=sit&ut=amet&nulla=nunc&sed=viverra&accumsan=dapibus&felis=nulla&ut=suscipit&at=ligula&dolor=in&quis=lacus",
    "https://vimeo.com/risus/semper.aspx?ligula=tortor&pellentesque=duis&ultrices=mattis&phasellus=egestas&id=metus&sapien=aenean&in=fermentum&sapien=donec&iaculis=ut&congue=mauris&vivamus=eget&metus=massa&arcu=tempor&adipiscing=convallis&molestie=nulla&hendrerit=neque&at=libero&vulputate=convallis&vitae=eget&nisl=eleifend&aenean=luctus&lectus=ultricies&pellentesque=eu&eget=nibh&nunc=quisque&donec=id&quis=justo&orci=sit&eget=amet&orci=sapien&vehicula=dignissim",
    "https://goo.ne.jp/nec.json?ante=lobortis&ipsum=est&primis=phasellus&in=sit&faucibus=amet&orci=erat&luctus=nulla&et=tempus&ultrices=vivamus&posuere=in&cubilia=felis&curae=eu&nulla=sapien&dapibus=cursus&dolor=vestibulum&vel=proin&est=eu&donec=mi&odio=nulla&justo=ac&sollicitudin=enim&ut=in&suscipit=tempor&a=turpis&feugiat=nec&et=euismod&eros=scelerisque&vestibulum=quam&ac=turpis&est=adipiscing&lacinia=lorem&nisi=vitae&venenatis=mattis&tristique=nibh&fusce=ligula&congue=nec&diam=sem&id=duis&ornare=aliquam&imperdiet=convallis&sapien=nunc&urna=proin&pretium=at&nisl=turpis&ut=a&volutpat=pede&sapien=posuere&arcu=nonummy&sed=integer&augue=non&aliquam=velit&erat=donec&volutpat=diam&in=neque&congue=vestibulum&etiam=eget&justo=vulputate&etiam=ut&pretium=ultrices&iaculis=vel&justo=augue&in=vestibulum&hac=ante&habitasse=ipsum&platea=primis&dictumst=in&etiam=faucibus&faucibus=orci&cursus=luctus&urna=et&ut=ultrices&tellus=posuere&nulla=cubilia&ut=curae&erat=donec&id=pharetra&mauris=magna&vulputate=vestibulum&elementum=aliquet&nullam=ultrices&varius=erat&nulla=tortor&facilisi=sollicitudin&cras=mi&non=sit&velit=amet&nec=lobortis&nisi=sapien&vulputate=sapien&nonummy=non&maecenas=mi&tincidunt=integer&lacus=ac&at=neque",
    "https://photobucket.com/sed/tincidunt/eu.aspx?ligula=arcu&pellentesque=adipiscing&ultrices=molestie&phasellus=hendrerit&id=at&sapien=vulputate&in=vitae&sapien=nisl&iaculis=aenean&congue=lectus&vivamus=pellentesque&metus=eget&arcu=nunc&adipiscing=donec&molestie=quis&hendrerit=orci&at=eget&vulputate=orci&vitae=vehicula&nisl=condimentum&aenean=curabitur&lectus=in&pellentesque=libero&eget=ut&nunc=massa&donec=volutpat&quis=convallis&orci=morbi&eget=odio&orci=odio&vehicula=elementum&condimentum=eu&curabitur=interdum&in=eu&libero=tincidunt&ut=in&massa=leo&volutpat=maecenas&convallis=pulvinar&morbi=lobortis&odio=est&odio=phasellus&elementum=sit&eu=amet&interdum=erat&eu=nulla&tincidunt=tempus&in=vivamus&leo=in&maecenas=felis&pulvinar=eu&lobortis=sapien&est=cursus&phasellus=vestibulum&sit=proin&amet=eu&erat=mi&nulla=nulla&tempus=ac&vivamus=enim&in=in&felis=tempor&eu=turpis&sapien=nec&cursus=euismod&vestibulum=scelerisque&proin=quam&eu=turpis&mi=adipiscing&nulla=lorem&ac=vitae&enim=mattis&in=nibh&tempor=ligula&turpis=nec&nec=sem&euismod=duis&scelerisque=aliquam&quam=convallis&turpis=nunc&adipiscing=proin&lorem=at&vitae=turpis&mattis=a&nibh=pede&ligula=posuere&nec=nonummy&sem=integer&duis=non&aliquam=velit",
    "http://intel.com/donec.json?nulla=nisl&integer=nunc&pede=nisl&justo=duis&lacinia=bibendum&eget=felis&tincidunt=sed&eget=interdum&tempus=venenatis&vel=turpis&pede=enim&morbi=blandit&porttitor=mi&lorem=in&id=porttitor&ligula=pede&suspendisse=justo&ornare=eu&consequat=massa&lectus=donec&in=dapibus&est=duis&risus=at&auctor=velit&sed=eu&tristique=est&in=congue&tempus=elementum&sit=in&amet=hac&sem=habitasse&fusce=platea&consequat=dictumst&nulla=morbi&nisl=vestibulum&nunc=velit&nisl=id&duis=pretium&bibendum=iaculis&felis=diam&sed=erat&interdum=fermentum&venenatis=justo&turpis=nec&enim=condimentum&blandit=neque&mi=sapien&in=placerat&porttitor=ante&pede=nulla&justo=justo&eu=aliquam&massa=quis&donec=turpis&dapibus=eget&duis=elit&at=sodales&velit=scelerisque&eu=mauris&est=sit&congue=amet&elementum=eros",
    "http://drupal.org/at/nunc/commodo/placerat/praesent/blandit.jpg?consequat=odio&metus=in&sapien=hac&ut=habitasse&nunc=platea&vestibulum=dictumst&ante=maecenas&ipsum=ut&primis=massa&in=quis&faucibus=augue&orci=luctus&luctus=tincidunt&et=nulla&ultrices=mollis&posuere=molestie&cubilia=lorem&curae=quisque&mauris=ut&viverra=erat&diam=curabitur&vitae=gravida&quam=nisi&suspendisse=at&potenti=nibh&nullam=in",
    "https://myspace.com/ante/nulla.jsp?ut=vestibulum&volutpat=ante&sapien=ipsum&arcu=primis&sed=in&augue=faucibus&aliquam=orci&erat=luctus&volutpat=et&in=ultrices&congue=posuere&etiam=cubilia&justo=curae&etiam=nulla&pretium=dapibus&iaculis=dolor&justo=vel&in=est&hac=donec&habitasse=odio&platea=justo&dictumst=sollicitudin&etiam=ut&faucibus=suscipit&cursus=a&urna=feugiat&ut=et&tellus=eros&nulla=vestibulum",
    "https://xrea.com/duis/at/velit.js?imperdiet=nibh&sapien=fusce&urna=lacus&pretium=purus&nisl=aliquet&ut=at&volutpat=feugiat&sapien=non&arcu=pretium&sed=quis&augue=lectus&aliquam=suspendisse&erat=potenti&volutpat=in&in=eleifend&congue=quam&etiam=a&justo=odio&etiam=in&pretium=hac&iaculis=habitasse&justo=platea&in=dictumst&hac=maecenas&habitasse=ut&platea=massa&dictumst=quis&etiam=augue&faucibus=luctus&cursus=tincidunt&urna=nulla&ut=mollis&tellus=molestie&nulla=lorem&ut=quisque&erat=ut&id=erat&mauris=curabitur&vulputate=gravida&elementum=nisi&nullam=at&varius=nibh&nulla=in&facilisi=hac&cras=habitasse&non=platea&velit=dictumst&nec=aliquam&nisi=augue&vulputate=quam&nonummy=sollicitudin&maecenas=vitae&tincidunt=consectetuer&lacus=eget&at=rutrum&velit=at&vivamus=lorem&vel=integer&nulla=tincidunt&eget=ante&eros=vel&elementum=ipsum&pellentesque=praesent&quisque=blandit&porta=lacinia&volutpat=erat&erat=vestibulum&quisque=sed&erat=magna&eros=at&viverra=nunc&eget=commodo&congue=placerat&eget=praesent&semper=blandit&rutrum=nam&nulla=nulla&nunc=integer&purus=pede&phasellus=justo&in=lacinia&felis=eget&donec=tincidunt&semper=eget&sapien=tempus&a=vel&libero=pede&nam=morbi&dui=porttitor&proin=lorem&leo=id&odio=ligula",
    "http://prlog.org/pretium/iaculis/justo/in/hac/habitasse/platea.js?elementum=in&eu=congue&interdum=etiam&eu=justo&tincidunt=etiam&in=pretium&leo=iaculis&maecenas=justo&pulvinar=in&lobortis=hac&est=habitasse&phasellus=platea&sit=dictumst&amet=etiam&erat=faucibus&nulla=cursus&tempus=urna&vivamus=ut&in=tellus&felis=nulla&eu=ut&sapien=erat&cursus=id&vestibulum=mauris&proin=vulputate&eu=elementum&mi=nullam&nulla=varius&ac=nulla&enim=facilisi&in=cras&tempor=non&turpis=velit&nec=nec&euismod=nisi&scelerisque=vulputate&quam=nonummy&turpis=maecenas&adipiscing=tincidunt&lorem=lacus&vitae=at&mattis=velit&nibh=vivamus&ligula=vel&nec=nulla&sem=eget&duis=eros&aliquam=elementum&convallis=pellentesque&nunc=quisque&proin=porta&at=volutpat&turpis=erat&a=quisque&pede=erat&posuere=eros&nonummy=viverra&integer=eget&non=congue&velit=eget&donec=semper&diam=rutrum&neque=nulla&vestibulum=nunc&eget=purus&vulputate=phasellus&ut=in&ultrices=felis&vel=donec&augue=semper&vestibulum=sapien&ante=a&ipsum=libero&primis=nam&in=dui&faucibus=proin&orci=leo&luctus=odio&et=porttitor&ultrices=id&posuere=consequat&cubilia=in",
    "https://delicious.com/consequat/varius/integer/ac/leo/pellentesque.js?curae=est&donec=lacinia&pharetra=nisi&magna=venenatis&vestibulum=tristique&aliquet=fusce&ultrices=congue&erat=diam&tortor=id&sollicitudin=ornare&mi=imperdiet",
    "https://ihg.com/quisque/ut/erat/curabitur.xml?mi=a&nulla=odio&ac=in&enim=hac&in=habitasse&tempor=platea&turpis=dictumst&nec=maecenas&euismod=ut&scelerisque=massa&quam=quis&turpis=augue&adipiscing=luctus&lorem=tincidunt&vitae=nulla&mattis=mollis&nibh=molestie&ligula=lorem&nec=quisque&sem=ut&duis=erat&aliquam=curabitur&convallis=gravida&nunc=nisi&proin=at&at=nibh&turpis=in&a=hac&pede=habitasse&posuere=platea&nonummy=dictumst&integer=aliquam&non=augue&velit=quam&donec=sollicitudin&diam=vitae&neque=consectetuer&vestibulum=eget&eget=rutrum&vulputate=at&ut=lorem&ultrices=integer&vel=tincidunt&augue=ante&vestibulum=vel&ante=ipsum&ipsum=praesent&primis=blandit&in=lacinia&faucibus=erat&orci=vestibulum&luctus=sed&et=magna&ultrices=at&posuere=nunc&cubilia=commodo&curae=placerat&donec=praesent&pharetra=blandit&magna=nam&vestibulum=nulla&aliquet=integer&ultrices=pede&erat=justo&tortor=lacinia&sollicitudin=eget",
    "http://p.Z3.net:2918/",
    "https://51.176.251.128:9/&@=/;/%ED/@#",
    "http://9.gov",
    "http://116.250.7.50/_;&%4B;&;&/*:&=//&%DE:///?#",
    "https://le-1.gov",
    "http://110.215.253.4/&=B:=%BE?@"
]
