#if !canImport(ObjectiveC)
import XCTest

extension URLParseSampleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__URLParseSampleTests = [
        ("testEdgeCases", testEdgeCases),
        ("testGeneratedURLs", testGeneratedURLs),
        ("testParseIPV4", testParseIPV4),
        ("testParsePath", testParsePath),
        ("testParseURI", testParseURI),
        ("testParseURIFull", testParseURIFull),
        ("testParseURIPerformance", testParseURIPerformance),
        ("testParseURIPerformance_FoundationURL", testParseURIPerformance_FoundationURL),
        ("testSimpleParse", testSimpleParse),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(URLParseSampleTests.__allTests__URLParseSampleTests),
    ]
}
#endif
