#if !canImport(ObjectiveC)
import XCTest

extension GrammarRuleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GrammarRuleTests = [
        ("testGramarRuleLookahead", testGramarRuleLookahead),
        ("testGramarRuleLookaheadWithKeyword", testGramarRuleLookaheadWithKeyword),
        ("testGramarRuleOrStopsAtFirstMatchFound", testGramarRuleOrStopsAtFirstMatchFound),
        ("testGrammarNamedOptional", testGrammarNamedOptional),
        ("testGrammarNamedRule", testGrammarNamedRule),
        ("testGrammarRecursive", testGrammarRecursive),
        ("testGrammarRuleArrayWithOneItemBecomesOptional", testGrammarRuleArrayWithOneItemBecomesOptional),
        ("testGrammarRuleBacktrackingFailedOneOrMoreRule", testGrammarRuleBacktrackingFailedOneOrMoreRule),
        ("testGrammarRuleBacktrackingFailedZeroOrMoreRule", testGrammarRuleBacktrackingFailedZeroOrMoreRule),
        ("testGrammarRuleChar", testGrammarRuleChar),
        ("testGrammarRuleComplexNonRecursive", testGrammarRuleComplexNonRecursive),
        ("testGrammarRuleComplexRecursive", testGrammarRuleComplexRecursive),
        ("testGrammarRuleComplexRecursiveWithLookaheadWithKeyword", testGrammarRuleComplexRecursiveWithLookaheadWithKeyword),
        ("testGrammarRuleDigit", testGrammarRuleDigit),
        ("testGrammarRuleDirectSequence", testGrammarRuleDirectSequence),
        ("testGrammarRuleKeyword", testGrammarRuleKeyword),
        ("testGrammarRuleLetter", testGrammarRuleLetter),
        ("testGrammarRuleMaximumLengthIgnoresWhitespaceAfterToken", testGrammarRuleMaximumLengthIgnoresWhitespaceAfterToken),
        ("testGrammarRuleMaximumLengthIn", testGrammarRuleMaximumLengthIn),
        ("testGrammarRuleMaximumLengthInWithGreedyRule", testGrammarRuleMaximumLengthInWithGreedyRule),
        ("testGrammarRuleMaximumLengthInWithZeroOrMoreRule", testGrammarRuleMaximumLengthInWithZeroOrMoreRule),
        ("testGrammarRuleOneOrMore", testGrammarRuleOneOrMore),
        ("testGrammarRuleOneOrMoreOr", testGrammarRuleOneOrMoreOr),
        ("testGrammarRuleOperatorDirectSequence", testGrammarRuleOperatorDirectSequence),
        ("testGrammarRuleOperatorDirectSequenceCollapseSequential", testGrammarRuleOperatorDirectSequenceCollapseSequential),
        ("testGrammarRuleOperatorOneOrMore", testGrammarRuleOperatorOneOrMore),
        ("testGrammarRuleOperatorOneOrMoreOnArray", testGrammarRuleOperatorOneOrMoreOnArray),
        ("testGrammarRuleOperatorOr", testGrammarRuleOperatorOr),
        ("testGrammarRuleOperatorOrCollapseSequential", testGrammarRuleOperatorOrCollapseSequential),
        ("testGrammarRuleOperatorSequence", testGrammarRuleOperatorSequence),
        ("testGrammarRuleOperatorSequenceCollapseSequential", testGrammarRuleOperatorSequenceCollapseSequential),
        ("testGrammarRuleOperatorZeroOrMore", testGrammarRuleOperatorZeroOrMore),
        ("testGrammarRuleOperatorZeroOrMoreOnArray", testGrammarRuleOperatorZeroOrMoreOnArray),
        ("testGrammarRuleOptional", testGrammarRuleOptional),
        ("testGrammarRuleOptionalRuleDescriptionWithMany", testGrammarRuleOptionalRuleDescriptionWithMany),
        ("testGrammarRuleOr", testGrammarRuleOr),
        ("testGrammarRulePassesIn", testGrammarRulePassesIn),
        ("testGrammarRulePassesInWithZeroOrMoreRule", testGrammarRulePassesInWithZeroOrMoreRule),
        ("testGrammarRulePerformance", testGrammarRulePerformance),
        ("testGrammarRuleRecursiveWithOptionalPerformance", testGrammarRuleRecursiveWithOptionalPerformance),
        ("testGrammarRuleRecursiveWithZeroOrMorePerformance", testGrammarRuleRecursiveWithZeroOrMorePerformance),
        ("testGrammarRuleSequence", testGrammarRuleSequence),
        ("testGrammarRuleWhitespace", testGrammarRuleWhitespace),
        ("testGrammarRuleZeroOrMore", testGrammarRuleZeroOrMore),
        ("testManualLexingPerformance", testManualLexingPerformance),
        ("testRecursiveGrammarRuleCreate", testRecursiveGrammarRuleCreate),
        ("testRecursiveGrammarRuleDescription", testRecursiveGrammarRuleDescription),
    ]
}

extension ParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParserTests = [
        ("testBacktracker", testBacktracker),
        ("testBacktrackerWorksMultipleTimesInSequence", testBacktrackerWorksMultipleTimesInSequence),
        ("testFindNext", testFindNext),
        ("testFindNextString", testFindNextString),
        ("testInitState", testInitState),
        ("testIsEof", testIsEof),
        ("testNext", testNext),
        ("testNextThrowsWhenAtEndOfString", testNextThrowsWhenAtEndOfString),
        ("testNextUsesOffsetForReading", testNextUsesOffsetForReading),
        ("testPeek", testPeek),
        ("testPeekForward", testPeekForward),
        ("testPeekForwardFailsWithErrorWhenPastEndOfString", testPeekForwardFailsWithErrorWhenPastEndOfString),
        ("testPeekThrowsErrorWhenEndOfString", testPeekThrowsErrorWhenEndOfString),
        ("testPeekUsesOffsetForPeeking", testPeekUsesOffsetForPeeking),
        ("testRangeMarker", testRangeMarker),
        ("testRangeMarkerEmpty", testRangeMarkerEmpty),
        ("testRangeMarkerReverseIndex", testRangeMarkerReverseIndex),
        ("testRewindToStart", testRewindToStart),
        ("testSafeIsNextChar", testSafeIsNextChar),
        ("testSafeIsNextCharWithOffset", testSafeIsNextCharWithOffset),
        ("testSkipToNext", testSkipToNext),
        ("testSkipToNextFailsIfNotFound", testSkipToNextFailsIfNotFound),
        ("testSkipToNextString", testSkipToNextString),
        ("testSkipToNextStringFailsIfNotFound", testSkipToNextStringFailsIfNotFound),
        ("testSkipToNextStringFailsIfParameterIsEmpty", testSkipToNextStringFailsIfParameterIsEmpty),
        ("testWithTemporaryIndex", testWithTemporaryIndex),
        ("testWithTemporaryIndexRewindsOnError", testWithTemporaryIndexRewindsOnError),
    ]
}

extension Parser_AdvanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Parser_AdvanceTests = [
        ("testAdvance", testAdvance),
        ("testAdvanceExpectingCurrent", testAdvanceExpectingCurrent),
        ("testAdvanceExpectingCurrentThrowsWhenAtEndOfString", testAdvanceExpectingCurrentThrowsWhenAtEndOfString),
        ("testAdvanceExpectingCurrentThrowsWhenNonMatching", testAdvanceExpectingCurrentThrowsWhenNonMatching),
        ("testAdvanceExpectingDoesNotAdvanceParserIndexOnError", testAdvanceExpectingDoesNotAdvanceParserIndexOnError),
        ("testAdvanceIf", testAdvanceIf),
        ("testAdvanceIfOptions", testAdvanceIfOptions),
        ("testAdvanceIfUsesOffset", testAdvanceIfUsesOffset),
        ("testAdvanceLengthAdvancingToEndOfString", testAdvanceLengthAdvancingToEndOfString),
        ("testAdvanceLength", testAdvanceLength),
        ("testAdvanceLengthThrowsErrorWhenPastEndOfString", testAdvanceLengthThrowsErrorWhenPastEndOfString),
        ("testAdvanceThrowsErrorWhenAtEndOfString", testAdvanceThrowsErrorWhenAtEndOfString),
        ("testAdvanceUntil", testAdvanceUntil),
        ("testAdvanceUntilRespectsEndOfString", testAdvanceUntilRespectsEndOfString),
        ("testAdvanceValidatingCurrent", testAdvanceValidatingCurrent),
        ("testAdvanceValidatingCurrentThrowsWhenAtEndOfString", testAdvanceValidatingCurrentThrowsWhenAtEndOfString),
        ("testAdvanceValidatingCurrentThrowsWhenNonMatching", testAdvanceValidatingCurrentThrowsWhenNonMatching),
        ("testAdvanceValidatingDoesNotAdvanceParserIndexOnError", testAdvanceValidatingDoesNotAdvanceParserIndexOnError),
        ("testAdvanceWhile", testAdvanceWhile),
        ("testAdvanceWhileRespectsEndOfString", testAdvanceWhileRespectsEndOfString),
        ("testAdvanceWithLengthEndingInEndIndex", testAdvanceWithLengthEndingInEndIndex),
        ("testCheckNext", testCheckNext),
        ("testCheckNextOptions", testCheckNextOptions),
        ("testCheckNextUsesOffset", testCheckNextUsesOffset),
        ("testConsumeMatch", testConsumeMatch),
        ("testConsumeMatchThrowsErrorWhenNonMatching", testConsumeMatchThrowsErrorWhenNonMatching),
        ("testNonMatchingAdvanceIf", testNonMatchingAdvanceIf),
        ("testNonMatchingCheckNext", testNonMatchingCheckNext),
        ("testSafeAdvance", testSafeAdvance),
        ("testSafeAdvanceStopsAtEndOfString", testSafeAdvanceStopsAtEndOfString),
    ]
}

extension Parser_ConsumeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Parser_ConsumeTests = [
        ("testConsumeLength", testConsumeLength),
        ("testConsumeLengthOffsetFromStart", testConsumeLengthOffsetFromStart),
        ("testConsumeLengthThrowsEndOfStringErrorIfLengthExceedsStringEndIndex", testConsumeLengthThrowsEndOfStringErrorIfLengthExceedsStringEndIndex),
        ("testConsumeString", testConsumeString),
        ("testConsumeUntil", testConsumeUntil),
        ("testConsumeUntilRespectsEndOfString", testConsumeUntilRespectsEndOfString),
        ("testConsumeWhile", testConsumeWhile),
        ("testConsumeWhileRespectsEndOfString", testConsumeWhileRespectsEndOfString),
        ("testConsumeWithLengthEndingInEndIndex", testConsumeWithLengthEndingInEndIndex),
    ]
}

extension TokenizerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TokenizerTests = [
        ("testAdvanceMatching", testAdvanceMatching),
        ("testAdvanceMatchingFailed", testAdvanceMatchingFailed),
        ("testAdvanceOver", testAdvanceOver),
        ("testAdvanceOverErrorMessage", testAdvanceOverErrorMessage),
        ("testAdvanceOverFailed", testAdvanceOverFailed),
        ("testAdvanceOverTokenType", testAdvanceOverTokenType),
        ("testAdvanceOverTokenTypeErrorMessage", testAdvanceOverTokenTypeErrorMessage),
        ("testAdvanceOverTokenTypeFailed", testAdvanceOverTokenTypeFailed),
        ("testAdvancesUntilStopsAtEndOfFile", testAdvancesUntilStopsAtEndOfFile),
        ("testAdvanceUntil", testAdvanceUntil),
        ("testAllTokens", testAllTokens),
        ("testAllTokensAtBeginningOfGrammar", testAllTokensAtBeginningOfGrammar),
        ("testAllTokensSpaced", testAllTokensSpaced),
        ("testAlternativeTokenizer", testAlternativeTokenizer),
        ("testBacktracker", testBacktracker),
        ("testBacktrackerWontEraseHasReadFirstTokenState", testBacktrackerWontEraseHasReadFirstTokenState),
        ("testBacktrackerWontWorkTwice", testBacktrackerWontWorkTwice),
        ("testBacktracking", testBacktracking),
        ("testBacktrackingWorksWithErrorsThrown", testBacktrackingWorksWithErrorsThrown),
        ("testConsumeTokenIfTypeIsMatching", testConsumeTokenIfTypeIsMatching),
        ("testConsumeTokenIfTypeIsNonMatching", testConsumeTokenIfTypeIsNonMatching),
        ("testFullToken", testFullToken),
        ("testFullTokenRange", testFullTokenRange),
        ("testFullTokenTokenString", testFullTokenTokenString),
        ("testFullTokenValue", testFullTokenValue),
        ("testInitWithLexer", testInitWithLexer),
        ("testMakeIterator", testMakeIterator),
        ("testSkipToken", testSkipToken),
        ("testSkipTokenWithLeadingWhitespace", testSkipTokenWithLeadingWhitespace),
        ("testToken", testToken),
        ("testTokenIsType", testTokenIsType),
        ("testTokenizeEofOnEmptyString", testTokenizeEofOnEmptyString),
        ("testTokenizerConsistencyWhenLexerIndexIsModifiedExternally", testTokenizerConsistencyWhenLexerIndexIsModifiedExternally),
        ("testTokenizeStream", testTokenizeStream),
        ("testTokenMatches", testTokenMatches),
        ("testTokenMatchesWithEmptyString", testTokenMatchesWithEmptyString),
        ("testTokenTypeIsAtBeginningOfGrammar", testTokenTypeIsAtBeginningOfGrammar),
        ("testTokenTypeIsType", testTokenTypeIsType),
        ("testTokenTypeMatches", testTokenTypeMatches),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GrammarRuleTests.__allTests__GrammarRuleTests),
        testCase(ParserTests.__allTests__ParserTests),
        testCase(Parser_AdvanceTests.__allTests__Parser_AdvanceTests),
        testCase(Parser_ConsumeTests.__allTests__Parser_ConsumeTests),
        testCase(TokenizerTests.__allTests__TokenizerTests),
    ]
}
#endif
